### ISSUE TITLE
GAMIC's volume might not have puse_width value

### ISSUE THREAD

**Issue by ReallyNiceGuy** [ARM-DOE/pyart#1004]
The format of GAMIC's volume states that pulse_width is an optional information.
PYART will raise an error in this situation, but it would be better if it didn't. I would like to know which value should be used instead.
I could put an explicit "None" there.
No code should break with this change, as the error will propagate to the usage point instead of the loading point.

**Comment by rcjackson** [comment]
What is the pulse width of your radar in degrees? That should be the value that goes there, which you may have to manually specify.

**Comment by rcjackson** [comment]
Could you send us an example file without a pulse_width field? I suspect we just need to put a default value of none in the reader in gamic_hdf5.py if there is no field found. @zssherman and I will take a look.

**Comment by mgrover1** [comment]
@zssherman can we close this via #1014 ?

**Comment by zssherman** [comment]
Yep closing!
