### ISSUE TITLE
Method of ‘plot_latlon_slice’ is missing？

### ISSUE THREAD

**Issue by 664787022** [ARM-DOE/pyart#1016]
```

import pyart
import matplotlib.pyplot as plt
import matplotlib as mpl
import cinrad
from cinrad.io.export import standard_data_to_pyart
import matplotlib.colors as colors
import netCDF4
import cartopy.crs as ccrs
import pyart
import cartopy.io.shapereader as shpreader
from pyart.filters import GateFilter
from pyart.map import grid_from_radars
import cartopy.crs as ccrs
import numpy as np
import os

filename='D:/20180916_12_20/T_RADR_I_Z9200_20180916150000_O_DOR_SAD_CAP_FMT.bin.bz2'

f = cinrad.io.StandardData(filename)

data=f.get_data(0,400,"REF")

display = pyart.graph.GridMapDisplay(data)

x, z, data = display.plot_latlon_slice("reflectivity", coord1=(120.2, 28.0), coord2=(121.1, 28.0),vmin=-10,vmax=10)
```

**After I run the above codes, it raised the following error:**
```
Traceback (most recent call last):

  File "C:\Users\asus\AppData\Local\Temp/ipykernel_1608/1292140421.py", line 1, in <module>
    x, z, data = display.plot_latlon_slice("reflectivity", coord1=(120.2, 28.0), coord2=(121.1, 28.5),vmin=-10,vmax=30)

AttributeError: 'GridMapDisplay' object has no attribute 'plot_latlon_slice' 
```

**I searched the document and found the method of 'plot_latlon_slice' do exist. What' wrong with that? Was this method deleted? How could I get a slice plot between two specific coordinates? By the way, dir(display) is shown as following:**
`dir(display)
Out[66]: 
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_find_nearest_grid_indices',
 '_get_label_x',
 '_get_label_y',
 '_get_label_z',
 '_label_axes_grid',
 '_label_axes_latitude',
 '_label_axes_longitude',
 'cartopy_coastlines',
 'cartopy_political_boundaries',
 'cartopy_states',
 'debug',
 'fields',
 'generate_filename',
 'generate_grid_title',
 'generate_latitudinal_level_title',
 'generate_longitudinal_level_title',
 'grid',
 'mappables',
 'origin',
 'plot_colorbar',
 'plot_crosshairs',
 'plot_grid',
 'plot_latitude_slice',
 'plot_latitudinal_level',
 'plot_longitude_slice',
 'plot_longitudinal_level']`

**Comment by 664787022** [comment]
> @664787022 There is no plot_latlon_slice in pyart. However I googled searched and it looks like there is in pyrad meteoswiss, a radar packaged based on a forked version of pyart, which is my guess where you saw the docs for it. If you want that functionality you need to use pyrad.

Thank you for your reply. but I find "plot_latlon_slice" in the following document ,
https://github.com/ARM-DOE/pyart/issues/1016#issuecomment-954831282
it is a pyart document not pyrad. Actually, i once used "plot_latlon_slice" in pyart before, for this reason i say this method is missing. Does pyart have other method to plot RHI between two specific coordinates?

**Comment by zssherman** [comment]
@664787022 Thats the pyrad meteoswiss fork of pyart. We don't have control over that sadly, so the docs you found is the docs for their meteoswiss fork of pyart, so you need to source install that version of pyart. https://github.com/MeteoSwiss/pyart @meteoswiss-mdr would we want to add this functionality to pyarts main repository? I can help with this if need be

**Comment by 664787022** [comment]
@zssherman Thanks! It works!
