### ISSUE TITLE
Example data link is broken again

### ISSUE THREAD

**Issue by asiyats** [ARM-DOE/pyart#1028]
The link provided in README.md is no longer working, page not found, please update the new link

The files used in these examples are available for download_.

.. _download: https://engineering.arm.gov/~jhelmus/pyart_example_data/

@zssherman @jjhelmus

**Comment by zssherman** [comment]
Thanks @asiyats for the heads up, I'll take a look and go about finding a more permanent location.

**Comment by zssherman** [comment]
Data link has been restored and the example data is accessible again. Leaving this issue open until we work on a more permanent location for the data.

**Comment by mgrover1** [comment]
@zssherman can we close this now that we have the example hosted in a permanent location?

**Comment by zssherman** [comment]
@mgrover1 One last thing, in the docs for the downloadable data the link is still https://engineering.arm.gov/~jhelmus/pyart_example_data/

There might be still one spot to change in the docs and we should be good.

**Comment by zssherman** [comment]
The link seen here:
https://arm-doe.github.io/pyart/examples/index.html
