### ISSUE TITLE
Determine Better Method of Dealing with Test Data

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1041]
Currently, the data are hosted on an ANL server, requiring users to download the data manually, move the data to the necessary directories, then build the docs. It would be useful to use a tool such as [Pooch](https://www.fatiando.org/pooch/latest/index.html) to help with this process, making it possible to build the example docs on Github Actions instead of running locally, then adding that to the docs.

**Comment by mgrover1** [comment]
For now, I created a demo repo [here](https://github.com/mgrover1/pyart-data-demo) to test this out - once it is ready, Ill submit a PR

**Comment by mgrover1** [comment]
Alrighty... [the prototype](https://github.com/mgrover1/pyart-data-demo) works 👍 with the syntax

```python
from pyart_datasets import get_test_data

radar = pyart.io.read_mdv(get_test_data('110635.mdv'))
```

This will make building the docs _much_ easier, especially the example gallery.

One of the remaining questions is whether this should be its own package (ex. `pyart_datasets`) or a module within PyART... 

@scollis @AdamTheisen @rcjackson @zssherman what are your thoughts here?

**Comment by zssherman** [comment]
@mgrover1 Sweet, I think this will be much better. Think jjhelmus link is going to be removed. We're going to use https://adc.arm.gov/pyart/example_data/ instead, as a heads up. I think for the actually code itself is pooch a python native package or does it have to be installed as a dependency? Trying to think if it's the later how to go about that to avoid increasing the dependency count.

**Comment by mgrover1** [comment]
@zssherman Sounds good! 

Pooch **does** need to installed as a dependency, but this is where we could think about whether we want this to be a _module_ within PyART, or create a separate package... I put some pros/cons to these approaches in [this afternoon's meeting notes](https://hackmd.io/eXMjluMdRMOEscaleNWYmQ)

**Comment by dopplershift** [comment]
Just wanted to add that Pooch is pure Python and has been pretty stable. MetPy has had 0 problems depending on it.

**Comment by zssherman** [comment]
@dopplershift Sweet sounds good! Yeah then I'm all for it being added. We can discuss more on the call today, but I have an idea of where to put it within pyart @mgrover1
