### ISSUE TITLE
Improving references of methods in Py-ART

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/pyart#1042]
Mentioned by users as well as digging through the code from years ago. Looking into adding better reference to journals etc to methods. Working on qpe methods at the moment.

**Comment by mgrover1** [comment]
Let's put a checklist together for this!

**Comment by mgrover1** [comment]
@zssherman are there any remaining references that need to be added?

**Comment by jrobrien91** [comment]
I can keep a list of missing/needed references as I go through PyART getting more familiar with the package.

**Comment by mgrover1** [comment]
@jrobrien91 could you share that list here? That would be super helpful!!

**Comment by zssherman** [comment]
@mgrover1 I'm not sure, alot of the older code I need to still go through. I opened this to kinda address them as they popped up as well.

**Comment by mgrover1** [comment]
# Py-ART Reference Checklist

Here is a list of modules and associated references that are added or still need to be added

## pyart.retrieve
- [ ] calculate_snr_from_reflectivity
