### ISSUE TITLE
Lat/Lon in Grid object

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#107]
I've noticed that the `lat` and `lon` variables in a `Grid` object are <i>no longer</i> the latitude and longitude corresponding to the `x` and `y` axes, i.e. `len(x) == len(lon)` and `len(y) == len(lat)`. The original grids @scollis created were like this. Instead it is now the latitude and longitude at the origin. This is fine, but for wind retrieval efforts we need to know the location of the radar in the grid, and this was easily done before by something like `j = abs(grid_lats - radar_lat).argmin()` to get the y index of the radar in the grid.

So I'd like to recommend that we include both the full latitude and longitude coordinates of the grid axes like we were before, as well as the latitude and longitude of the radar itself in the `Grid` object.

**Comment by jjhelmus** [comment]
Need to add methods to the Grid object for returning arrays of latitude, longitude and altitude for all point in the grid.  This should likely be done at the same time as adding similar functionality to the Radar object as in issue #247
