### ISSUE TITLE
BUG: Running into issues with `RadarDisplay.plot_vpt` time axis

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1083]
When setting `time_axis_flag` = True within `plot_vpt`, Matplotlib runs into error stating:

```python
TypeError: Dimensions of C (600, 1736) are incompatible with X (1736) and/or Y (601); see help(pcolormesh)
```

@zssherman mentioned that he had fixed this issue in another plotting view (#1025), which provides some hints on how to fix this issue..

**Comment by zssherman** [comment]
fixed in, #1381
