### ISSUE TITLE
Attenuation correction

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#109]
I'm not sure if I'm missing something with the process of correcting for attenuation in rain, but should I be expecting the <i>corrected</i> reflectivity field to have <i>any</i> gates with <b>lower</b> reflectivity than the input reflectivity field? Because I certainly do, and pretty much for every gate.

FYI these results are from the C-SAPR MDV file `092825.mdv`.

The first image is the two-panel comparison of raw versus corrected. Just with your eye you should be able to see that the corrected field is lower in most regions.

![20110425_092825_csapr](https://f.cloud.github.com/assets/2049028/1727254/4ddb9d32-629c-11e3-9bf7-5813fa112f4a.png)

The second image is the difference field, in this case Z_corr - Z_raw. Note the negative color scale limits. The mean of this difference field for the first elevation (0.5 deg) was about -5 dBZ.

![20110425_092825_csapr_diff](https://f.cloud.github.com/assets/2049028/1727268/80a277c2-629c-11e3-91e9-7683d84817d0.png)

These results were produced with the following,

``` python
phidp_corr, kdp_corr = phase_proc_lp(radar, -2.0, self_const=60000.0, low_z=10.0,
                                     high_z=53.0, min_phidp=0.01, min_ncp=0.5,
                                     min_rhv=0.8, fzl=3900.0, overide_sys_phase=False,
                                     nowrap=291, LP_solver='cylp_mp', window_len=35,
                                     proc=6, debug=False, really_verbose=False)

spec_at, ze_corr = calculate_attenuation(radar, -2.0, doc=15, fzl=3900.0, rhv_min=0.8, 
                                         ncp_min=0.5, a_coef=0.06, beta=0.8)
```

**Comment by godofyoga** [comment]
How can i  get radar system z_offset and phase offset?

**Comment by josephhardinee** [comment]
Yogesh, you should move this to it's own issue.

**Comment by godofyoga** [comment]
Thank you
