### ISSUE TITLE
BUG: NEXRAD Level3 DPR  product reading

### ISSUE THREAD

**Issue by jaypotnis** [ARM-DOE/pyart#1114]
I am doing project on Quantitative Precipitation Estimation using WSR 88D Radar. I am comparing NEXRAD L3 Digital Precipitation Rate with actual Rain Rate from TRMM GV Rain Gauges.

Looks like the data being read in the below snippet does not scale the rain rate data correctly.
https://github.com/ARM-DOE/pyart/blob/a68bed26f6380eecbf1042c94bd4da0b60fb2da7/pyart/io/nexrad_level3.py#L297-L300

The way I am seeing the data, I need to multiply the whole data by 10. To convert it to the proper scale (i.e. inch/mm).

Below are some Z-RR plots at a constant height. Z is obtained from NEXRAD L2 data. Additionally I am also multiplying the Pyart read DPR data by 25.4 to convert it to mm/hr. But that is not expected by pyart as L3 DPR data is supposed to have default unit as inch/mm.

L3 DPR data after reading it through pyart and converting to mm/hr.
![2015_rr_vs_z_0 5_gauge_SFL_068](https://user-images.githubusercontent.com/64808466/163691993-1111948c-4983-45cf-a0c7-e1b767ee7125.png)

L3 DPR data after reading it through pyart, multiplying by 10 and converting to mm/hr.
![2015_rr_vs_z_0 5_gauge_SFL_068 (1)](https://user-images.githubusercontent.com/64808466/163692079-f8066ea3-af40-4758-8693-803d8622a632.png)

I hope this explanation helped. This is not a significant issue but would still be good to avoid confusion while reading the DPR data.

Btw, thanks for creating this wonderful tool for reading L3 data. There are not a lot of tools that do that. Found it very helpful. :)

**Comment by mgrover1** [comment]
Thank you @jaypotnis for pointing this out. We will look into implementing a solution to this, or you are welcome to submit a pull request (PR) with the fix if you are interested. Happy to help with this process!

**Comment by dopplershift** [comment]
I'm confused, why isn't it expected? In the XDR product, the unit are encoded:
```
Unit = inches/hour
```
So it seems to me that needing to multiply by 25.4 to get mm/hr is correct?

**Comment by mgrover1** [comment]
The units pyart returns are wrong - it is supposed to inches/hour.

Also, I think I found the issue... we are assuming the data is an 8 bit integer

https://github.com/ARM-DOE/pyart/blob/main/pyart/io/nexrad_level3.py#L219

but according to the Level3 documentation, this field is a 16 bit integer 
<img width="1169" alt="Screen Shot 2022-04-14 at 3 57 07 PM" src="https://user-images.githubusercontent.com/26660300/163874120-51b2b99e-f0f3-4a05-8fb9-13aebbffafb3.png">

Currently working on a PR to fix both of these issues, and add some tests...

**Comment by mgrover1** [comment]
Alrighty - I tested this out on one of the TRACER cases (a field campaign coordinated by ARM), which includes disdrometers/other ground precipitation measurements. 

The laser disdrometer (ld), located near the airport, measured a maximum precipitation rate of 95 mm/hr, which corresponds to 3.7 inches/hour. 

<img width="1458" alt="Screen Shot 2022-04-18 at 4 22 43 PM" src="https://user-images.githubusercontent.com/26660300/163884297-a43b9c75-692b-4020-9bd4-40a150ecd0a8.png">

NEXRAD data shows rain rates similar, with a few values **much** higher (>7 inches/hour)... here is the rain rate (`DPR`) field at the time closest to that peak disdrometer data:
<img width="495" alt="Screen Shot 2022-04-18 at 4 51 34 PM" src="https://user-images.githubusercontent.com/26660300/163884479-3ff7ce01-590c-473f-844a-85d814224845.png">

**Comment by mgrover1** [comment]
Keeping this open for now - here is the figure from the previous method (before the merged PR)
<img width="506" alt="Screen Shot 2022-04-18 at 5 01 47 PM" src="https://user-images.githubusercontent.com/26660300/163885434-70a0fbfb-82f0-4f7f-bce0-ddb93cfc84bc.png">

@dopplershift / @jaypotnis does this look like it's solved this issue?

**Comment by dopplershift** [comment]
It certainly looks more sensible to me.

And no prob @mgrover1, taking a look at this has led me to fix a different bug in MetPy's own support for this product.

**Comment by jaypotnis** [comment]
The rain rate certainly looks better now. Thanks for a quick resolution on this @mgrover1
