### ISSUE TITLE
Ensure monotonically increasing time when writing cf/Radial files

### ISSUE THREAD

**Issue by rcjackson** [ARM-DOE/pyart#1142]
When doing this latest run of CMAC2.0 I noticed that when the cf/Radial files were written that the time was not always monotonically increasing. I wonder if it is worth putting in a check for this when we write cf/Radial files and then sort the data accordingly if it is not.

**Comment by zssherman** [comment]
@rcjackson With the discovered argument in the sigmet reader, can we close this or do we want to change the code to be more transparent for this?
