### ISSUE TITLE
ENH: Add a new example showing hydrometeor classification and QPE functionality

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1260]
At the recent ERAD tutorials, there were some great new tutorials put together by the meteoswiss/meteofrance team (@wolfidan @jfigui )

[Sample notebook](https://openradarscience.org/erad2022/notebooks/pyart/exercice1_swiss_thunderstorm.html)

It would be nice to have a concise example of this in our examples gallery!

**Comment by mgrover1** [comment]
@wolfidan following up here - would this be something you would be interested in working together on?

**Comment by wolfidan** [comment]
Hi @mgrover1 , sorry for the delay, Yes I will try to add this in the examples gallery as soon as possible

**Comment by mgrover1** [comment]
I think splitting these up, and then adding a more detailed blog post bringing these together... I see the blog post section as more full-workflow focused
