### ISSUE TITLE
Publish wheels on PyPI ?

### ISSUE THREAD

**Issue by neutrinoceros** [ARM-DOE/pyart#1266]
Hi, I know this is a stretch, but would it be possible to start publishing some wheels on PyPI ?
I am aware that binaries are available on conda, I'm asking because amr-pyart get installed on yt's CI and costs about 2min to build on each job.

I am not familiar with pyart, is there a technical reason why wheel installs cannot be supported ?

**Comment by mgrover1** [comment]
Yeah - we can consider publishing individual wheels on PyPI! The main limitation has been the trmm_rsl package, which is a C package that is not available within Python.

**Comment by mgrover1** [comment]
We would also need a wheel for each cython version/OS (ex. `arm_pyart-1.12.7.post18-cp310-cp310-macosx_11_0_arm64.whl`)

**Comment by mgrover1** [comment]
@neutrinoceros we have started a PR moving toward this, any feedback or help there would be greatly appreciated!

**Comment by neutrinoceros** [comment]
I will take a look tomorrow, thank you very much for putting it together so quickly !

**Comment by zssherman** [comment]
@neutrinoceros We closed the issue, but just pinging, it looks like the build wheels are now available on PyPI!

**Comment by mgrover1** [comment]
Thanks for all your help here @neutrinoceros !

**Comment by neutrinoceros** [comment]
Yup I saw that, thank you very much for being so reactive on this ! We are already seeing the result as a net ~2min gain on all CI jobs at yt, that will easily save hours of CPU time a week !
