### ISSUE TITLE
get_sweep/put_sweep method 

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#129]
Suggestion to add a get_sweep and put_sweep method to the Radar object which would extract or store a given sweep for a field.  This could also take care of masking or removing locations where the antenna_transition indicate that the radar was in transition.   Downstream functions (plotting, correcting) should then be updated to use this functionality.

- [x] get_sweep (implemented via the `extract_sweeps`)
- [x] put_sweep (implemented via `join_radars`)

**Comment by jjhelmus** [comment]
A get_field method was added to the Radar object in08e08e  which implements some of the described functionality.

**Comment by jjhelmus** [comment]
Still need to add an option to filter rays based on the antenna_transition when this attribute is available.  Similar functionality should also be added to the Sweep object in issue #242

**Comment by ron819** [comment]
Any chance this will be implemented soon?
