### ISSUE TITLE
radardisplay does not recognize c-sapr "sector" plot type 

### ISSUE THREAD

**Issue by mvanlierwalq** [ARM-DOE/pyart#1293]
tryping to plot the csapr file houcsapr2cfrS2.a1.20220617.190001.nc, display.plot throws an error owing to unknown plot type "sector" : `ValueError: unknown scan_type sector`
can this be added to pyart?

**Comment by mgrover1** [comment]
Yeah... currently "sector" is not one of these options, but we can consider adding it! Treating it the same as a PPI... which I think would be the right assumption @mvanlierwalq

**Comment by zssherman** [comment]
Yeah agreed, it should be a simple fix

**Comment by mvanlierwalq** [comment]
@zssherman thanks! will have to wait until tonight or tomorrow, having trouble connecting to my computer. will let you know.

**Comment by mgrover1** [comment]
@mvanlierwalq any updates here? Did the fix work?

**Comment by zssherman** [comment]
fixed in #1294 can be reopened if need be.
