### ISSUE TITLE
ENH: Add keyword add_lines in method plot_grid in gridmapdisplay

### ISSUE THREAD

**Issue by jfigui** [ARM-DOE/pyart#1297]
On occasion you would like to have the grid lines but not the coast maps in the plot. Separating the two would be useful (see https://github.com/MeteoSwiss/pyart/blob/dev/pyart/graph/gridmapdisplay.py)

**Comment by mgrover1** [comment]
I think this is also related to #1229 ...

**Comment by mgrover1** [comment]
Would you be interested in submitting a PR similar to the enhancement you added to the meteoswiss fork? @jfigui

**Comment by jfigui** [comment]
@mgrover1 ,
Yes, I can do that. I will try to find a slot to do it in the next two weeks. Pin me again if you see that nothing has happened by then :)
