### ISSUE TITLE
Issue with echo_class.py

### ISSUE THREAD

**Issue by swatelet** [ARM-DOE/pyart#1305]
Hi all,

I noticed that the line 157 (if 'frequency' in radar.instrument_parameters:) of echo_class.py generates this error when instrument_parameters of a radar object is set to None:

"TypeError: argument of type 'NoneType' is not iterable"

I would suggest to add a check of None on line 157, what do you think?

Cheers,
Sylvain

**Comment by mgrover1** [comment]
Hi @swatelet - thanks for catching this. I think that sounds like a reasonable solution. Would you be interested in implementing that fix?

**Comment by swatelet** [comment]
Thanks but unfortunately I have no time for that right now, but feel free to do it.

**Comment by zssherman** [comment]
I'll take a crack at this shortly.

**Comment by mgrover1** [comment]
Closed by #1306
