### ISSUE TITLE
ODIM_H5 reader

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#131]
Add a reader for the ODIM_H5 [format](http://www.eumetnet.eu/sites/default/files/OPERA_2008_03_WP2.1b_ODIM_H5_v2.1.pdf).  Daniel Michelson can provide sample files if needed.

**Comment by jjhelmus** [comment]
PR #195 added initial support for the ODIM format.  Once this is code is more complete and moved into the `pyart.io` namespace this issue can be close.

**Comment by jjhelmus** [comment]
Currently no instrumental parameters are extracted from ODIM files, so the `instrument_parameters` attribute of the returned **Radar** instance is set to `None`.  The 'how' group of the file contains a number of instrument parameters which should be included.

**Comment by scollis** [comment]
So we have a basic reader for ODIM HDF5. I think this issue can be closed and new issues can be opened to track improvements or bugs with the current system. If I am mistaken please feel free to re-open
