### ISSUE TITLE
Add an example of adding the station name to the NEXRAD reader

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1354]
We have received a few different questions related to using older (pre-2008) NEXRAD data, which does not have the station name in the file itself, which is needed to add the location of the radar.

see #1353 and #1273

We should add an example showing users how to add the station upon reading in the data, which helps with this issue.

**Comment by zssherman** [comment]
@mgrover1 I can take a shot at this, just need to find an older file. I'll check those issues and write up an example
