### ISSUE TITLE
BUG: netCDF4.Dataset arrays

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#140]
Bug might be a bit too harsh, but it should be noted that when using `netCDF4.Dataset` to read in data arrays, the array <b>will not be</b> a `numpy.ma.core.MaskedArray` when none of the values in the array are equal to the fill value, even if the variable has a `_FillValue` key (or equivalent) . Instead it will be read as a `numpy.ndarray`. This can cause issues when scripts depend on accessing the `mask` attribute of NumPy masked arrays.

Should we make sure there is consistency in the 'data' keys of `Radar` and `Grid` objects? Could use the `isinstace()` built-in to check the type, and change accordingly.

**Comment by jjhelmus** [comment]
From some recent testing I have done using the [`np.ma.getmaskarray`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.getdata.html) and [`np.ma.getdata`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.getdata.html) functions works very well when designed functions which work with ndarray and masked arrays.

**Comment by jjhelmus** [comment]
An update.  The  [`np.ma.getmaskarray`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.getdata.html) and [`np.ma.getdata`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.getdata.html) functions work as a reliable method for determining the data and mask from a NumPy **ndarray** or **MaskedArray**.  These are the suggested method to use in Py-ART algorithms which work with data which may or may not be masked, for example field data.  

Closing this issue.
