### ISSUE TITLE
Mention Cfradial Version in read_cfradial

### ISSUE THREAD

**Issue by Ockenfuss** [ARM-DOE/pyart#1406]
Currently, the API documentation of `read_cfradial` does not mention any version number of the Cfradial standard.
Although [Cfradial version 2](https://github.com/NCAR/CfRadial) officially still has draft status, it might be worth to mention which cfradial version is expected by `read_cfradial`, especially since versions 1.x and 2.x are incompatible.

**Comment by zssherman** [comment]
@Ockenfuss We can update the documentation to reflect the version expected! Yeah I agree, I don't see it in the docs so it would be useful to have. The current reader was designed for 1.4 cfradial. Xradar which is what Py-ART will be using down the road will also have compatibility for version 2 and datatrees.

**Comment by Ockenfuss** [comment]
@zssherman Really nice to hear that you plan to integrate xradar and Datatree with Py-ART, getting to work those three tools together is exactly what I was originally trying to achieve!

**Comment by zssherman** [comment]
Of course! @mgrover1 has been leading the efforts on this integration, and can provide more information if need be on it!
