### ISSUE TITLE
Bug: issue when compiling cython files for RSL with Cython 3.0

### ISSUE THREAD

**Issue by wolfidan** [ARM-DOE/pyart#1441]
* Py-ART version: 1.15.2
* Python version: 3.10.0
* Operating System: Ubuntu

### Description

Dear Py-ART team,
I noticed an issue when trying to compile the RSL cython files during Py-ART installation (from main branch).
The error is :

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              sweep.h.nrays = nrays
              for nray in range(nrays):
                  ray = _rsl_h.RSL_new_ray(nbins)
                  sweep.ray[nray] = ray
                  ray.h.nbins = nbins
                  ray.h.f = RSL_F_LIST[vol_num]
                                      ^
      ------------------------------------------------------------

      pyart/io/_rsl_interface.pyx:120:32: Cannot assign type 'float (*)(Range) except *' to 'float (*)(Range) noexcept'

I think it has to do with the use of Cython 3.0 again. I think you might not have encountered this issue because RSL tests are currently skipped from the CI (this is our case as well at MeteoSwiss), however during the generation of a conda package (with the conda feedstack), the Azure pipeline will fail because there it installs RSL libraries and tries to compile the Py-ART wrappers.

I managed to find a fix by using 

    cdef (float (*)(_rsl_h.Range) noexcept) * RSL_F_LIST = [
        _rsl_h.DZ_F, _rsl_h.VR_F, _rsl_h.SW_F, _rsl_h.CZ_F, _rsl_h.ZT_F,
        _rsl_h.DR_F, _rsl_h.LR_F, _rsl_h.ZD_F, _rsl_h.DM_F, _rsl_h.RH_F,
        _rsl_h.PH_F, _rsl_h.XZ_F, _rsl_h.CD_F, _rsl_h.MZ_F, _rsl_h.MD_F,
        _rsl_h.ZE_F, _rsl_h.VE_F, _rsl_h.KD_F, _rsl_h.TI_F, _rsl_h.DX_F,
        _rsl_h.CH_F, _rsl_h.AH_F, _rsl_h.CV_F, _rsl_h.AV_F, _rsl_h.SQ_F,
        _rsl_h.VS_F, _rsl_h.VL_F, _rsl_h.VG_F, _rsl_h.VT_F, _rsl_h.NP_F,
        _rsl_h.HC_F, _rsl_h.VC_F, _rsl_h.VR_F, _rsl_h.SW_F, _rsl_h.VR_F,
        _rsl_h.SW_F, _rsl_h.DZ_F, _rsl_h.CZ_F, _rsl_h.PH_F, _rsl_h.SD_F,
        _rsl_h.DZ_F, _rsl_h.DZ_F]

    cdef (_rsl_h.Range (*)(float) noexcept) * RSL_INVF_LIST = [
        _rsl_h.DZ_INVF, _rsl_h.VR_INVF, _rsl_h.SW_INVF, _rsl_h.CZ_INVF,
        _rsl_h.ZT_INVF, _rsl_h.DR_INVF, _rsl_h.LR_INVF, _rsl_h.ZD_INVF,
        _rsl_h.DM_INVF, _rsl_h.RH_INVF, _rsl_h.PH_INVF, _rsl_h.XZ_INVF,
        _rsl_h.CD_INVF, _rsl_h.MZ_INVF, _rsl_h.MD_INVF, _rsl_h.ZE_INVF,
        _rsl_h.VE_INVF, _rsl_h.KD_INVF, _rsl_h.TI_INVF, _rsl_h.DX_INVF,
        _rsl_h.CH_INVF, _rsl_h.AH_INVF, _rsl_h.CV_INVF, _rsl_h.AV_INVF,
        _rsl_h.SQ_INVF, _rsl_h.VS_INVF, _rsl_h.VL_INVF, _rsl_h.VG_INVF,
        _rsl_h.VT_INVF, _rsl_h.NP_INVF, _rsl_h.HC_INVF, _rsl_h.VC_INVF,
        _rsl_h.VR_INVF, _rsl_h.SW_INVF, _rsl_h.VR_INVF, _rsl_h.SW_INVF,
        _rsl_h.DZ_INVF, _rsl_h.CZ_INVF, _rsl_h.PH_INVF, _rsl_h.SD_INVF,
        _rsl_h.DZ_INVF, _rsl_h.DZ_INVF]

at lines 75 to 97 of https://github.com/ARM-DOE/pyart/blob/main/pyart/io/_rsl_interface.pyx (notice the addition of noexcept)

It will compile, but I am not totally sure if the tests pass because I have some issues with the flex library for which a very old version is required for the RSL library...I'll keep you posted,

Cheers

**Comment by mgrover1** [comment]
Thanks for the heads up here @wolfidan !
