### ISSUE TITLE
ENH: Reading WMO-FM301 (CfRadial2) files

### ISSUE THREAD

**Issue by alan-weatherradar** [ARM-DOE/pyart#1516]
* Py-ART version: 1.17.0
* Python version:
* Operating System: 

### Description

Are there any plans to extend the io module to support the new WMO-FM301 standard? 

Regards 
Alan Seed

**Comment by mgrover1** [comment]
Thanks for the question here @alan-weatherradar - the plan is to support it through xradar https://github.com/openradar/xradar . Full support for this is in the Py-ART 2.0 plan, which is scheduled to be released in September of this year.

**Comment by mgrover1** [comment]
Now that we merged https://github.com/openradar/open-radar-data/pull/69 , we can add an example from xradar/Py-ART showcasing this functionality
