### ISSUE TITLE
Missing get_sweep_keys from xradar

### ISSUE THREAD

**Issue by waarmond** [ARM-DOE/pyart#1553]
* Py-ART version: git master
* Python version: 3.10
* Operating System: Linux from scratch
* [xradar](https://github.com/openradar/xradar): 0.<s>5</s>3.0

### Description

`ImportError: cannot import name 'get_sweep_keys' from 'xradar.util' (/usr/lib/python3.10/site-packages/xradar/util.py)`

### What I Did

```
import pyart
```

Introduced by https://github.com/openradar/xradar/issues/164 ?

**Comment by zssherman** [comment]
@waarmond get_sweep_keys was added fairly recently to xradar. Your xradar is 0.5.0 on your system? My guess was maybe an outdated xradar.

Wait I see you mention 0.5.0 above.

Hmm, will have to look into it

**Comment by waarmond** [comment]
@zssherman My error. I've started the python instance before updating xradar.

**Comment by mgrover1** [comment]
@waarmond - is it working with the updated version?

**Comment by zssherman** [comment]
@mgrover1 Sounds good, thanks!

**Comment by mgrover1** [comment]
@waarmond - following up here, is it working?

**Comment by mgrover1** [comment]
Closing this with the new release
