### ISSUE TITLE
ENH: Update documentation of `hydroclass_semisupervised` for X band classification.

### ISSUE THREAD

**Issue by RBhupi** [ARM-DOE/pyart#1561]
* Py-ART version: All
* Python version: All
* Operating System: All

### Description
In `hydroclass_semisupervised` if the frequency information in `radar.instrument_parameters` is missing, function defaults to C band and warns radar frequency is unknown. The documentation is not clear on how to get hydrometeor class for X band in this situation. Need for adding band information to radar.instrument_parameters should be clearly stated, may be with an example.

### What I Did
- [x] Update documentation to clarify that classification for X band needs frequency information in the radar object or it defaults to C band.
- [x] Give example for correctly adding X band information to radar.instrument_parameters.

**Comment by RBhupi** [comment]
Example of warning

```
# Get classification
hydromet_class = pyart.retrieve.hydroclass_semisupervised(
    radar, 
    refl_field="corrected_reflectivity",
    zdr_field="corrected_differential_reflectivity",
    kdp_field="filtered_corrected_specific_diff_phase",
    rhv_field="RHOHV",
    temp_field="sounding_temperature",
)
```

> /Users/bhupendra/anaconda3/envs/data/lib/python3.12/site-packages/pyart/retrieve/echo_class.py:663: UserWarning: Radar frequency unknown. Default coefficients for C band will be applied.

**Comment by zssherman** [comment]
Thanks for the discussion! Would you be willing to do a PR to expand on the warning etc for it?

**Comment by RBhupi** [comment]
Thanks @zssherman ! I have sent a PR for documentation update.
