### ISSUE TITLE
BUG: CI failing due to shapely/numpy incompatability

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1615]
* Py-ART version: 1.18.6
* Python version: >3.10
* Operating System: All

### Description

The CI is failing due to shapely being incompatible with the latest numpy release
https://github.com/shapely/shapely/issues/2109

### What I Did

We should wait for a release from shapely, which should come quickly, which will resolve this issue, as well as add some additional pins within the environment files.

**Comment by EwoutH** [comment]
Shapely 2.0.6 is now released, which resolved the issue with NumPy 2.1.0.

**Comment by zssherman** [comment]
Passing on our end. closing
