### ISSUE TITLE
DOC: Migrate from github pages to readthedocs

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1624]
* Py-ART version: All
* Python version: All
* Operating System: All

### Description

With moving to Py-ART 2.0 , we should move to readthedocs, similar to the rest of the open radar community xradar/cmweather/etc. 

### What I Did

Used read the docs and would like documentation previews and such

**Comment by mgrover1** [comment]
@kmuehlbauer - any suggestions on how to deal with redirects from the previous github pages links?

**Comment by kmuehlbauer** [comment]
There is something like rediraffe where links can be redirected. 

I've always trusted Google to be fast enough to fix it. :grinning:
