### ISSUE TITLE
CI: Windows builds failing

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/pyart#1655]
* Python version: 3.9, 3.10, 3.11, 3.12
* Operating System: Windows

### Description

During post cleanup we get this error for all windows builds:
Could not find micromamba activate pyart-dev in C:\Users\runneradmin\.bash_profile
The process 'C:\Users\runneradmin\micromamba-bin\micromamba.exe' failed with exit code 1

Running into the same issue with ACT as well.

**Comment by mgrover1** [comment]
I am digging into this today @zssherman

**Comment by zssherman** [comment]
@mgrover1 No worries, I just reran the tests now to see if something was down for actions or if it was fixed.

**Comment by mgrover1** [comment]
It could be related to the issues raised here?
https://github.com/mamba-org/micromamba-releases/issues/58

**Comment by zssherman** [comment]
@mgrover1 Yeah looks like it.
