### ISSUE TITLE
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. 

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/pyart#1671]
* Py-ART version: Current
* Python version: 3.12
* Operating System: All

### Description
/home/runner/work/pyart/pyart/pyart/map/gates_to_grid.py:118: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)

I think I have a solution for some of these, however would we want a check for when the array has multiple values? I think in rare cases we do for mobile radars and I believe we take a mean in the gridding code.

**Comment by mgrover1** [comment]
Good to close with #1673 ?

**Comment by zssherman** [comment]
Yep! Closing.
