### ISSUE TITLE
BUG: netCDF4 and writing large files

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#177]
Is anyone aware of an inability of `netCDF4` to properly write large files (e.g. writing a <i>large</i> radar object) when `format = 'NETCDF4'`? Basically I was able to write an X-band file when `format = 'NETCDF3_CLASSIC'`, and read this file after. However, when `format = 'NETCDF4'`, calling `pyart.io.write_cfradial` <i>finished</i>, but I was getting a segmentation fault when trying to read it after. This file was 200-300 MB in size.

**Comment by jjhelmus** [comment]
@kirknorth Are you still investigating this?

**Comment by kirknorth** [comment]
@jjhelmus I'm not actively investigating this issue at his time. Give me a couple of days to run some tests. When I created this issue I running Python 2.6 with netCDF4 version 1.0.4, however I now have another VE running Python 2.7 with netCDF4 version 1.1.1 and reason to suspect this won't be an issue in this VE.

**Comment by jjhelmus** [comment]
@kirknorth Any updates on this issue or can it be closed?

**Comment by kirknorth** [comment]
@jjhelmus I am no longer running into this issue, likely due to the changes in my VE as stated in my last comment.

**Comment by jjhelmus** [comment]
Thanks for the update, closing this issue.
