### ISSUE TITLE
New potential mapping routine

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#182]
@jjhelmus and @scollis, I have a new mapping routine on a [test branch](https://github.com/kirknorth/pyart/tree/map-test). It makes use of SciPy's `cKDTree` object, but unlike the current implementation, it does not explicitly loop over the entire analysis grid, and therefore it is quite fast. For example, I can map every field (15 total) found in a CSAPR surveillance file with ~ 6 million gates onto a Cartesian domain with ~ 2 million grid points in ~ 1 minute using a Cressman distance-dependent weighting technique. This routine also has the ability to do a nearest neighbor technique, which for the same inputs mentioned previously, takes ~ 30 seconds.

Another enhancement is that MaskedArrays are handled quite nicely and every radar field's masked data is handled independently, therefore a `refl_filter_flag` is not required to remove potentially bad gates (assuming input data is <i>good</i>). What this means is fields like normalized coherent power or cross correlation ratio can be mapped everywhere, as they should be (in my opinion). See below for a couple examples.

<b>Normalized coherent power</b>
![sgpcsaprmmcgi7 c2 ncp cressman 1111](https://cloud.githubusercontent.com/assets/2049028/4142032/27de0e64-33b4-11e4-8bb2-0946931a5ab5.png)

<b>Reflectivity factor</b>
![sgpcsaprmmcgi7 c2 ze cressman 1111](https://cloud.githubusercontent.com/assets/2049028/4142041/40e052b4-33b4-11e4-924d-2aa6e0bd6b0d.png)

**Comment by jjhelmus** [comment]
Expanding on my last comment on an improvement of the current gridding routine.  Currently the gridding algorithm in Py-ART loops over all points in the grid, finds radar gates within a given distance by searching a k-d or Ball tree for each grid point and then performing a Cressman or Barnes weighting to interpolate the values of the grid points.  This is computationally expensive are requires at least N log(M) operations (N : number of grid points, M : number of gates) for finding gates and significantly more time if multiple gates fall into the search distance.  A more efficient algorithm would loop over the radar gates, determining which grid points they should contribute to and performing the weighted interpolation using an online algorithm.  This algorithm would have a linear time complexity in M which should have better performance that the existing method.

**Comment by zssherman** [comment]
Map gates to grid, closing for now.
