### ISSUE TITLE
Cartesian locations for radar gates

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#246]
A helper method should be added to the Radar object for returning the x, y, and z Cartesian locations from the radar location for a give or all gates in a radar volume (or sweep).

This functionality was suggested by Timothy Lang.

**Comment by scollis** [comment]
Great idea.
We have something in there:
https://github.com/ARM-DOE/pyart/blob/master/pyart/io/common.py#L60

I am also planning on building a module (as part of CMAC2.0 work) to map 
profile data to radar gates.. So this will help with this (as I need Z)

I may just go ahead and write this in coming days
