### ISSUE TITLE
Starting wradlib bridge, how to do integration

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#257]
I am working on the first use of wradlib  in Py-ART. We need to:
A) Have the bridge components in the right places (ie io, correct etc..)
B) Allow conditional import as wradlib will be an optional dependency..
The first thing we will start with will be texture calculations as per:
http://nbviewer.ipython.org/github/scollis/openvap/blob/master/development/cmac2/notebooks/1%20exploration%20of%20X%20and%20C%20SAPR%20data%20and%20texture.ipynb
Proposal:
create a new subdirectory pyart/bridge
create file pyart/bridge/wradlib_bridge.py

allow each __init__.py in the various modules to do a conditional import from pyart/bridge/wradlib_bridge.py to populate the namespaces.

Thoughts?

**Comment by jjhelmus** [comment]
Concerning the location of the modules and populating the pyart namespace with the various wradlib wrapped function I would prefer to keep all of the bridge and wrapping code in the bridge directory.  A function can then be defined in the bridge `__init__.py` file which populates the pyart.correct, pyart.retrieve, etc namespaces with the wrapped functions.  I made an [example module](https://github.com/jjhelmus/python_dynamic_namespace_test) which does just this.  The [`populate_namespace_with_extra` function](https://github.com/jjhelmus/python_dynamic_namespace_test/blob/master/sayhello/extra/__init__.py#L1) inserts the function defined in the extra directory into the packages namespaces.

**Comment by scollis** [comment]
Thanks @jjhelmus I have followed you instructions in PR #259 and testing shows this is a good way.
