### ISSUE TITLE
ODIM_H5: test for missing `how` group

### ISSUE THREAD

**Issue by swnesbitt** [ARM-DOE/pyart#287]
I am using `read_odimh5` and the files I am using, produced from OPERA BUFR through `bbufr` do not contain the `how` group.

This is causing the read routine to crash because it is expected, even though the routine later on has contingencies for this.  I have not found an elegant workaround for this, but to make it work brute force I to create an empty H5 file and then create an attribute, and then use that for evaluating later if I have an empty `how` attribute class.  I don't think I want to monkey with the existing datafile (and write to it, creating an empty `how` class).  This would get inserted at line 126 in `pyart/pyart/aux_io/odim_h5.py`.
```
import os
if os.path.exists('/tmp/tmp.h5'):
    os.remove('/tmp/tmp.h5')
hfiletmp=h5py.File('/tmp/tmp.h5', 'w')
subgrp = hfiletmp.create_group("how")
ds1_how=subgrp.attrs
os.remove('/tmp/tmp.h5')
```
This is obviously not a great way to do this, since in parallel processing this could get messy.  Any thoughts?

I have placed an example file here: <a href="https://dl.dropboxusercontent.com/u/54789242/misc/RMA1_4003_02_TH_20150502T062920Z.BUFR.H5">Example ODIM_H5 file from Cordoba, Argentina</a>.

**Comment by jjhelmus** [comment]
Thanks for finding this @swnesbitt and for bringing it to our attention.

The **ds1_how** variable is being used as a dictionary from which attributes are pulled if the correct key exists.  If there is no how Group in the file (which is allowed according to the standards) then an empty dictionary can take the place of this Attribute object.

I implemented this change in PR #288.  With this in place I was able to read the in example file without issue.  It did not contain any field data (I think this was intended) but the metadata was read correctly.

Feel free to re-open this issue if PR #288 does not fix this issue completely.
