### ISSUE TITLE
Trapp and Doswell weighting in gridding methods

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#349]
In [Trapp and Doswell (2001)](http://dx.doi.org/10.1175/1520-0426%282000%29017%3C0105:RDOA%3E2.0.CO;2) a modified Barnes type weighting is recommended for objective analysis.  An option to apply weighting of this type should be included in the `map_to_grid` and `map_gates_to_grid` functions.  See PR #158 for an early implementation and further discussion.

**Comment by scollis** [comment]
This can be closed now. If there is further work in this area please reopen or start a new issue
