### ISSUE TITLE
RadarDisplay_Airborne is broken

### ISSUE THREAD

**Issue by gamaanderson** [ARM-DOE/pyart#371]
RadarDisplay_Airborne is broken in [here](https://github.com/ARM-DOE/pyart/blob/master/pyart/graph/radardisplay_airborne.py#L244) because gatefilter was not added as an argument of `plot_sweep_grid`. By the way, there are no tests for this class.

**Comment by jjhelmus** [comment]
Good catch @gamaanderson.  I added the parameter to the function call.  I've been meaning to add some additional unit tests to Py-ART to up the coverage, PR #373 will track the work.
