### ISSUE TITLE
Plot azimuthal cross section of ppi

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#398]
As suggested by @nguy on the mailing list it would be convenient if a azimuthal cross section of a PPI could be visualized without needing to first create a RHI-like radar instance using `pyart.util.cross_section_ppi`.  **RadarDisplay** method names of `plot_ppi_azimuth` and `plot_vert_azimuth` were suggested.

**Comment by nguy** [comment]
Just submitted a PR that addresses this issue.

**Comment by jjhelmus** [comment]
Thanks @nguy.  Will close this issue once PR #405 is merged.
