### ISSUE TITLE
Function to mask/remove high value gates at the edge of sweeps

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#407]
As suggested in nguy/artview#107 a method for removing the 'ring' of high value gates at the edge of sweeps would make a good addition to Py-ART.  A simple implementation is as follows:

``` Python
radar = pyart.io.read('some_file.nc')
# insure that the reflectivity field is a masked array
radar.fields['reflectivity']['data'] = np.ma.array(radar.fields['reflectivity']['data'])
# mask out the last gates in each sweep
radar.fields['reflectivity']['data'][:, -10:] = np.ma.masked
```

Such a feature would fit well in the `pyart.correct` namespace.

**Comment by scollis** [comment]
In addition it would be nice to write a procedure to detect this.. most 
radars I have seen using a test signal use a constant dBm .. so writing 
code that works out how many gates have within a certain stdev could be 
easy to implement.. (i'll give this a go)
