### ISSUE TITLE
Incomplete and incorrect developer reference introduction

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#412]
The introduction to the [developer reference manual](http://arm-doe.github.io/pyart-docs-travis/dev_reference/index.html) is incomplete and incorrect.  A better reading would be:

```
The intended audience of this guide is developers who use Py-ART. For a more
general introduction to Py-ART aimed at users see the User Reference Manual.

This guide provides  documentation for all modules, function, methods, and classes within Py-ART,
both those in the public API and private members.
 
Documentation is broken down by directory and module.
```

This introduction is generated from the [docs/source/dev_reference/index.rst](https://github.com/ARM-DOE/pyart/blob/master/doc/source/dev_reference/index.rst)

This issue was created to help a new Py-ART developer learn our development workflow, please do not submit a PR against this issue unless you are that developer.

**Comment by Rumpkie** [comment]
Ping
