### ISSUE TITLE
Bug in add_field() grid object

### ISSUE THREAD

**Issue by bdolan44** [ARM-DOE/pyart#424]
In 'grid.py', 'add_field' function:

Line 79         nz, ny, nx = self.fields[self.fields.keys[0]]['data'].shape

Is missing () after keys such that it should read:

Line 79         nz, ny, nx = self.fields[self.fields.keys()[0]]['data'].shape

(I was getting error: builtin_function_or_method' object has no attribute '__getitem__')

Yay! I have contributed to PyArt!

**Comment by kirknorth** [comment]
Hi @bdolan44, this issue was actually recently fixed in PR #409, which means you may want to fetch the latest set of commits to Py-ART's master branch.

**Comment by bdolan44** [comment]
Whoops, sorry about that. I'll grab the latest! Thanks!

**Comment by kirknorth** [comment]
No worries, it still counts as contributing! :smile:

**Comment by scollis** [comment]
Of course it does! Thanks Brenda!

Kirk North wrote:
