### ISSUE TITLE
The toa parameter is interpreted differently in the two gridding methods

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#442]
The `toa` parameter control the height above which gates are excluded from the gridding algorithm.  This parameter is interpreted differently by the two gridding routines.  

In the 'map_gates_to_grid' the distance of the gate above the radar is added to the offset of the radar from the grid and compared against toa (toa is the height above grid origin).  

In 'map_to_grid' the distance of the gates above the radar is compared directly to toa (toa is the height above the radar).  

A uniform interpretation of toa should be used in both gridding methods.

**Comment by gamaanderson** [comment]
So we have three options,

1. height above origin
2. height above radar
3. height above see level

I'm for the third one!

**Comment by jjhelmus** [comment]
Another option is to remove to `toa` parameter entirely and have these gates removed by the gate filter.  Adding `{include/exclude}_{above/below}_{height/altitude}` methods to the GateFilter for including/excluding gates based upon their height above the radar or altitude should make possible.

**Comment by scollis** [comment]
Exactly.. TOA was introduced to speed gridding by rejecting gates that 
will never have returns in them.. Gatefilter effectively handles this now.

Jonathan J. Helmus wrote:
