### ISSUE TITLE
odimh5 support for RHI, PPI and sector PPI objects

### ISSUE THREAD

**Issue by joshuass** [ARM-DOE/pyart#445]
_pyART only appears to support PVOL objects in odimh5_
Single PPI scans and sector scans are defined as SCAN objects
RHI scans are defined as ELEV objects

See page 10 of the specifications doc for more information
http://www.eumetnet.eu/sites/default/files/OPERA2014_O4_ODIM_H5-v2.2.pdf

**Comment by jjhelmus** [comment]
@joshuass Can you provide example files of any of these scan modes?  Implementing support for the reading of these files is much easier with examples to work from.

**Comment by swnesbitt** [comment]
I have a functional code that can do this (at least the output from BALTRAD
bufr2hdf5 with an Argentinean radar file), just haven't uploaded it to the
archive.

It is in my fork of pyART.

-Steve

On Thu, Dec 17, 2015 at 3:34 AM, Jonathan J. Helmus <
notifications@github.com> wrote:

> @joshuass
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joshuass&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=f1noYkw00dsrdmemoBo3B_epdsF_RY2-OAGWjzSrXxY&s=unybmv8KrZi56zmoX4Y6MCxUhB8K74mQMLyNf2-6IAY&e=>
> Can you provide example files of any of these scan modes? Implementing
> support for the reading of these files is much easier with examples to work
> from.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARM-2DDOE_pyart_issues_445-23issuecomment-2D165430612&d=BQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=oh_IyBh3p6AhkrNBZyzmmDfeXg2WKrzfthPLOoHreWM&m=f1noYkw00dsrdmemoBo3B_epdsF_RY2-OAGWjzSrXxY&s=nWQXdZX1wuXVGisqW7I-qlUX12xYKs7gh4aA9EErerE&e=>
> .
>



-- 
Steve Nesbitt, Associate Professor
Department of Atmospheric Sciences, University of Illinois at
Urbana-Champaign
105 S. Gregory St., MC223, Urbana, IL 61801-3070  USA
voice : +1.217.244.3740  fax : +1.217.244.1752
internet : snesbitt@illinois.edu ;
https://www.atmos.illinois.edu/people/snesbitt ;
http://publish.illinois.edu/snesbitt

**Comment by joshuass** [comment]
Hi,

Here is an example RHI file
https://dl.dropboxusercontent.com/u/2037428/test_odimh5_files/uq-xpol_rhi_20151104_184723.h5
Here is an example SPPI file
https://dl.dropboxusercontent.com/u/2037428/test_odimh5_files/uq-xpol_sppi_20151210_162502.h5

I can get the sector PPI files working in pyart by changing the object type to PVOL and setting the azimuth manually. It appears pyART isn't reading the azstart and azstop values for sector PPIs.

Cheers,

**Comment by jjhelmus** [comment]
Thanks for the example files @joshuass.  I'll look into adding support to Py-ART for reading in these types of files.

**Comment by joshuass** [comment]
Can confirm RHI and PPI odimh5 files are working fine are working perfectly with the new odim reader. You can close this issue and #484 . Thanks for getting it to this point! :+1:

**Comment by jjhelmus** [comment]
Thanks for the conformation @joshuass, closing.
