### ISSUE TITLE
ODIMH5 PPI orientiation bug

### ISSUE THREAD

**Issue by joshuass** [ARM-DOE/pyart#484]
Hi,

Just an easy fix bug. The new version of py-ART (1.6) shows PPIs rotated 90 degrees anticlockwise. I had no issues in v1.5 with the same datasets.

[Link to ODIMH5 file](https://www.dropbox.com/s/s7dygcipt5ti15o/201512152330Kurnell.h5?dl=0)

[Link to ipynb file](https://github.com/uq-crg/rapic_to_pyart/blob/master/Kurnell_tor_20151215.ipynb)

Cheers,
J

**Comment by jjhelmus** [comment]
@joshuass can you elaborate a bit on the bug you are seeing?  When I plot the seventh tilt from the linked ODIM file I get the same results with Py-ART 1.5.0, 1.6.0 and the currently master:

## Py-ART 1.5.0:
![figure_150](https://cloud.githubusercontent.com/assets/1050278/12991800/9487bcf2-d0d6-11e5-8358-465c0dfbe4c8.png)

## Py-ART 1.6.0:
![figure_160](https://cloud.githubusercontent.com/assets/1050278/12991802/96af1700-d0d6-11e5-96a4-f9837c8bf06a.png)



## Py-ART 1.7.0.dev

![figure_master](https://cloud.githubusercontent.com/assets/1050278/12991812/a47a86a8-d0d6-11e5-9c8d-0108ee10a1e2.png)

**Comment by joshuass** [comment]
Hi @jjhelmus 

I've done some more investigation and found the source of this issue

@scollis  ipynb of the event used odim_h5 data generated by an older converter where the dataset#/data#/where/a1gate variable was always set to 0. The data is oriented correctly in this case.
notebook: https://github.com/scollis/notebooks/blob/master/Kurnell.ipynb
old odim file: https://www.dropbox.com/s/i5afnrlbdoskzmk/old_201512152330Kurnell.h5?dl=0

I copied his notebook and used the new converter, where the a1gate is now correctly set to the starting azimuth in the scan (248 in this case). Data is rotated CC ~90deg
notebook: https://github.com/uq-crg/rapic_to_pyart/blob/master/Kurnell_tor_20151215.ipynb
data: https://www.dropbox.com/s/s7dygcipt5ti15o/201512152330Kurnell.h5?dl=0

The datasets within these two files have exactly the same specification according to the ODIM standard 2.2, e.g., the northern most ray is first regardless of the a1gate. I suspect py-ART is reading the a1gate and offsetting the data azimuth?

Let me know what you think!

**Comment by joshuass** [comment]
Found this issue in the py-ART code.
https://github.com/ARM-DOE/pyart/blob/master/pyart/aux_io/odim_h5.py#L218

the a1gate isn't used to orientate the data in odimh5 files according to the specifications, the northward most ray is always the first row.

See section 5.1 of...
http://www.eumetnet.eu/sites/default/files/OPERA2014_O4_ODIM_H5-v2.2.pdf

**Comment by jjhelmus** [comment]
Agreed.  There are a number of improvements and bugs that need to be fixed in Py-ART's odim h5 reader, #445.  If you want to take a shot at fixing the code up a bit @joshuass feel free. I have it on my to-do list but I can't give a timeline as to when I will get to it.

**Comment by joshuass** [comment]
I'll have a go at this small bug @jjhelmus , but I'm afraid my python skills are a little lacking to review the entire ODIM reader. Once I finish my PhD in a few months I'll have plenty of time to perfect these skills and contribute more.

Also, you'll be interested to hear we've started building a complete volumetric archive of Australia radar data in odim for open access to researchers. I've introduced py-art to the Australian community with a number of notebooks Scott wrote and the response has been very promising. Hopefully py-art will be the tool of choice in Australia soon enough :)

**Comment by jjhelmus** [comment]
@joshuass I'm excited to head about the creation of an Australian radar archive, would be a great resource for the community.  Let me or Scott know if you need any materials to introduce or show off Py-ART.  

I'm traveling this week and may have a some time on the plane or in the evening to improve Py-ART ODIM support.  I'll keep this issue updated with any progress.

**Comment by joshuass** [comment]
Cheers! It would be great to host a few notebooks of select cases (Scott already has enough written) with some specific documentation for odim files. Not much really. I've given it a start here [link](https://github.com/uq-crg/rapic_to_pyart/wiki/Using-rapic_to_odim) , but happy to move everything onto a DOE page. I'll raise it as a request once the archive is finished.
