### ISSUE TITLE
3d visualization of radar data using a GIS viewer.

### ISSUE THREAD

**Issue by Rumpkie** [ARM-DOE/pyart#492]
A useful new feature for rendering radar data onto a map would be to create pyart io output that would be compatible with GIS toolkits like the webgl virtual planet Cesiumjs from http://cesiumjs.org/
Here is a netCDF grid http://cesiumjs.org/demos/GridViz.html example:
![image](https://cloud.githubusercontent.com/assets/11509667/13446809/2de4b2b0-dfdc-11e5-95c1-ed392d50d468.png)

another example… something like an RHI plot. 
http://abhishekvpotnis.me/data-curtains/
![image](https://cloud.githubusercontent.com/assets/11509667/13446830/4c3aa49a-dfdc-11e5-8bad-e05f49308474.png)

Could be useful, would definitely be cool.

How it would work:

Pyart io would write the selected and processed radar object into a GEOJSON file similar to the process that radar display uses to get the data ready for matplotlib.

Cesium would be used to display interact with the data, and jquery would be used to add view controls.

**Comment by jjhelmus** [comment]
This would be interesting, although I think would require a decent amount of work.  I know there has been some work to output geo-referenced raster images of radar fields using Py-ART for GIS but I don't think GeoJSON has been suggested before.

**Comment by scollis** [comment]
I see no obvious path to a solution in the near future. I am closing. If there is interest open a new issue or re-open this.

**Comment by AdamTheisen** [comment]
@scollis @zssherman was the ability to export in GeoJSON ever implemented?  Was thinking it would make for an interesting and interactive way to plot and monitor radar data using plotly chloropleth  plots.

**Comment by zssherman** [comment]
@AdamTheisen sadly it has not, the closest thing to Pyart and 3d is yt project PR, but they haven't made progress in a bit.
