### ISSUE TITLE
CyLP and CVXOPT unit tests skipped on Travis CI

### ISSUE THREAD

**Issue by jjhelmus** [ARM-DOE/pyart#496]
Currently Travis CI is skipping unit tests which depend on cylp or cvxopt, this should be fixed.  For example [this build](https://travis-ci.org/ARM-DOE/pyart/jobs/114306856).

**Comment by jjhelmus** [comment]
The issue with CyLP and CVXOPT is that both packages have Python extensions that link to liblapack and libblas which depend on libgfortran.  The symbols provided by the conda libgfortran libraries are not sufficient for the lapack and blas libraries installed on the system.  Force removing this package results in the system libgfortran library being used.  

A more preferable solution to this would be to not use the system provided liblapack or libblas at all and instead meet these dependencies with conda packages which are linked to the conda provided libgfortran.  This will take time, I will look into it when I move the cylp and cxvopt_glpk recipes over to conda-forge.

**Comment by scollis** [comment]
Sounds reasonable


Jonathan J. Helmus wrote:
