### ISSUE TITLE
min_radius in grid_mapper.py

### ISSUE THREAD

**Issue by mvanlierwalq** [ARM-DOE/pyart#516]
Hi folks, the code where min_radius is used in ROI calculation in grid_mapper right now reads 
`        r = (z_factor * (zg - zg_off) +
             xy_factor * np.sqrt((xg - xg_off)**2 + (yg - yg_off)**2) +
             min_radius)`

Should it not read
`r = np.maximum(min_radius, z_factor * (zg - zg_off) +
             xy_factor * np.sqrt((xg - xg_off)**2 + (yg - yg_off)**2) `
?

**Comment by jjhelmus** [comment]
Good catch, yes the minimum should be an alternative to the calculated ROI but added to the calculation.  I'll submit a fix tomorrow.
