### ISSUE TITLE
issue plotting file read from GAMIC HDF5 due to byte instead of string in field unit

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#581]
File is a test file from the X-SAPR2 in the Azores
stability-ppi_XSAPR2_20160610160808_00.h5

`my_display = pyart.graph.RadarMapDisplay(ena_radar)
my_display.plot_ppi_map('reflectivity')`
results in
`/Users/scollis/anaconda/envs/pyart35/lib/python3.5/site-packages/pyart/graph/common.py in generate_colorbar_label(standard_name, units)
    115 def generate_colorbar_label(standard_name, units):
    116     """ Generate and return a label for a colorbar. """
--> 117     return standard_name.replace('_', ' ') + ' (' + units + ')'
    118 
    119 

TypeError: Can't convert 'bytes' object to str implicitly
`

and 

`print(ena_radar.fields['reflectivity']['units'])`
results in

`b'dBZ'`

setting
ena_radar.fields['reflectivity']['units'] = 'dBZ'

fixes the issue

**Comment by jjhelmus** [comment]
Looks like the variable used to populate this entry is not decoded from the byte-string provided by h5py.  Will submit a fix shortly.
