### ISSUE TITLE
Problem while reading lassen/rapic files: '_RSL_AVAILABLE' is not defined

### ISSUE THREAD

**Issue by vlouf** [ARM-DOE/pyart#589]
When I try to read a lassen file with pyart I have this error:
`pyart.io.read(inpath + fd)`
NameError: name '_RSL_AVAILABLE' is not defined

TRMM RSL library is installed and linked (through conda-forge). `pyart.io.read(inpath + fd, use_rsl=True)` does not work either. However `pyart.io.read_rsl(inpath + fd)` works perfectly.

`python -c "import pyart; pyart._debug_info()"`

miniconda3/lib/python3.5/site-packages/pyart/map/grid_mapper.py:40: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  from .ball_tree import BallTree
Py-ART version: 1.6.0

---- Dependencies ----
Python version: 3.5.2
NumPy version: 1.11.1
SciPy version: 0.18.0
matplotlib version: 1.5.1
netCDF4 version: 1.2.4

---- Optional dependencies ----
TRMM RSL version: b'v1.49'
CyLP: MISSING
PyGLPK version: MISSING
CVXOPT version: MISSING
basemap version: MISSING
nose version: 1.3.7

**Comment by jjhelmus** [comment]
@vlouf Thanks for reporting this.  Looks like the `_RSL_AVAILABLE` variable was mistakenly removed from the `auto_read` module in PR #411, specifically ab839d.  Will have a fix up shortly. 

Until then the work around of using the `pyart.io.read_rsl` is your best bet.
