### ISSUE TITLE
Documentation error in function pyart.map.grid_mapper.grid_from_radars

### ISSUE THREAD

**Issue by meteoswiss-mdr** [ARM-DOE/pyart#591]
Grid limits should be described as:

grid_limits : 3-tuple of 2-tuples
Minimum and maximum grid location (inclusive) in meters for the z, y, x coordinates

the order of y and x should be inversed

**Comment by jjhelmus** [comment]
Good catch @meteoswiss-mdr, fix will be out shortly.
