### ISSUE TITLE
Constant Altitude Plan Position Indicator (CAPPI)

### ISSUE THREAD

**Issue by meteoswiss-mdr** [ARM-DOE/pyart#597]
It would be convenient to create a griddisplay class in line with the radardisplay class to be able to plot CAPPIs in km units.

In addition it may be convenient to be able to plot gridmapdisplay and radarmapdisplay in km units.

**Comment by jjhelmus** [comment]
@meteoswiss-mdr I agree completely with the recommendation. Thanks for submitting this.  Adding labels.

**Comment by scollis** [comment]
So Just checking I understand @meteoswiss-mdr : x and y axes in km instead of lat/lon?

**Comment by meteoswiss-mdr** [comment]
Yes, that is what I meant

Sent from my iPhone

On 13 Jul 2017, at 18:23, Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


So Just checking I understand @meteoswiss-mdr<https://github.com/meteoswiss-mdr> : x and y axes in km instead of lat/lon?

**Comment by vlouf** [comment]
I recently needed to do a CAPPI, so I have coded up a notebook that do just that:
https://github.com/vlouf/radar_cappi

It wouldn't be a lot of work to add this to Py-ART. Strictly speaking, no interpolation is made, just looking for the nearest neighbour at each grid point for a given altitude.

**Comment by meteoswiss-mdr** [comment]
My own code for this can be found here:

https://meteoswiss-mdr.github.io/pyrad/_modules/pyrad/graph/plots_vol.html#plot_cappi

**Comment by mustafaalicelik** [comment]
I guess this feature hasn't been added to pyart yet? I need some help on this.

**Comment by zssherman** [comment]
@mustafaalicelik I'll see if I can get the pyrad implementation provided by meteoswiss into pyart.

**Comment by mustafaalicelik** [comment]
Any improvement?

**Comment by scollis** [comment]
Can’t you just make a single level grid?

-sent from a mobile device-

**Comment by zssherman** [comment]
@mustafaalicelik I'm hoping to have a try at this sometime tomorrow or early next week.

**Comment by hamidrizvi** [comment]
@vlouf 
> I recently needed to do a CAPPI, so I have coded up a notebook that do just that:
> https://github.com/vlouf/radar_cappi
> 
> It wouldn't be a lot of work to add this to Py-ART, so I can do this if you want.
> 
> Strictly speaking, no interpolation is made, just looking for the nearest neighbour at each grid point for a given altitude.

Hello Sir,
I am a master's student working on a quantitative precipitation estimation, for my thesis, I need to compute cappi as well as i've to retrieve rainfall from the same!!,
I just want to know few things from your code;
1. Why did you created azimuth, doesn't your file contain that already?
2. When I change the cappi_altitude in the same code, plot comes the same for every altitude, why? (I was trying to input altitude of 2000, but it only worked for 2 and 1  and those are also alike, there should be difference in cappi at 2 km altitude in comparison with 1km)
3. What is this interpolation method called?
Please have a look at my notebook and help me if possible.! 
https://github.com/hamidrizvi/Analyzing-Precipitation-Data/blob/master/CAPPI-Copy23.ipynb

**Comment by vlouf** [comment]
Hi @hamidrizvi ,

Frankly I don't remember well, it was quite some time ago.
1/ It's to convert the azimuth angle (North is 0 degree and going clockwise) to mathematical angle (0 degree is x-axis and going counter-clockwise).
2/ Altitude is in meter I believe, you should use 2000, not 2.
3/ Nearest neighbour.

**Comment by gabrielcassol** [comment]
Has this CAPPI product already been added to pyart?

**Comment by zssherman** [comment]
@gabrielcassol Hello! At the moment, it has not, still on our list for an addition before the next big release.

**Comment by syedhamidali** [comment]
@gabrielcassol I would suggest having a look at this, https://github.com/syedhamidali/CAPPI-NETCDF/blob/main/simple_cappi.ipynb

You can make the data gridded, then plot it at whatever height you want. Here I have plotted Max-CAPPI in this example.

**Comment by mgrover1** [comment]
@syedhamidali - is there any interest in contributing this to the main Py-ART repo? If not, we can draft something from our side and ping you for review.

**Comment by syedhamidali** [comment]
@mgrover1 Sounds good! I’ll get started on a script for plotting max_cappi with any projection. If that aligns with what you’re thinking, awesome. If not, just let me know what you’d like me to focus on instead.
