### ISSUE TITLE
Trouble converting Rainbow files to Cfradial

### ISSUE THREAD

**Issue by srbrodzik** [ARM-DOE/pyart#601]
I'm unsuccessfully trying to read some Rainbow format radar data into a radar structure (so that I can output cfradial files).

In [1]: import pyart

##
##
##     JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119 

In [2]: file = '/home/disk/bob/olympex/xband/rainbowFiles/RAW_DOPVOL1_A/DBZ/2016011207500600dBZ.azi'

In [3]: radar = pyart.aux_io.read_rainbow_wrl(file)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6b5fa6247414> in <module>()
----> 1 radar = pyart.aux_io.read_rainbow_wrl(file)

/home/disk/shear2/brodzik/.local/lib/python2.7/site-packages/pyart/aux_io/rainbow_wrl.pyc in read_rainbow_wrl(filename, field_names, additional_metadata, file_field_names, exclude_fields, **kwargs)
    263     _range['data'] = np.linspace(
    264         start_range+r_res / 2., float(nbins - 1.) * r_res+r_res / 2.,
--> 265         nbins, dtype='float32')
    266 
    267     # containers for data

TypeError: linspace() got an unexpected keyword argument 'dtype'

I don't know why that line is causing trouble since dtype is a valid keyword argument for np.linspace and float32 is a valid option.  

Has anyone tried to do such a thing successfully?  I've attached the rainbow file in question to this email in case someone wants to give it a try. (2016011207500600dBZ.zip)

FYI, I'm using pyart v1.8.0.dev and numpy v1.8.2.  The file in question is Rainbow v5.43.10 but I get the same error when trying to read in a Rainbow v5.34.16 file (which is supposedly supported by this version of pyart).   I've attached this older file as well (2013070308340000dBuZ.zip).

[2013070308340000dBuZ.zip](https://github.com/ARM-DOE/pyart/files/516980/2013070308340000dBuZ.zip)

Thanks.

Stacy
[2016011207500600dBZ.zip](https://github.com/ARM-DOE/pyart/files/516975/2016011207500600dBZ.zip)

**Comment by jjhelmus** [comment]
The issue here is that the *dtype* parameter was not added the NumPy's `linspace` function [until version 1.9.0](https://docs.scipy.org/doc/numpy/release.html#dtype-parameter-added-to-np-linspace-and-np-logspace).  Upgrading to a newer version of NumPy should fix the issue.

I'll have a fix up shortly which will allow these function to be used with older versions of NumPy which do not have this new feature.
