### ISSUE TITLE
Altitude data available from ARM sonde data stream

### ISSUE THREAD

**Issue by kirknorth** [ARM-DOE/pyart#606]
I'm working on some VAD code and came across this potential issue. Altitude information is available in ARM sonde data streams, yet heights are computed from pressure measurements in [line 59](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/arm_sonde.py#L59) of `read_arm_sonde`. Just curious why this is.  Here's a plot of the differences between the two for a test file [here](http://www.meteo.mcgill.ca/~kirk/). 

![height_difference](https://cloud.githubusercontent.com/assets/2049028/19373842/246a24b6-9195-11e6-96b8-851feddb26de.png)

According to the variable attributes, sonde altitude measurements should be in meters above mean sea level, which matches what's written in the docs of `HorizontalWindProfile` class.

**Comment by jjhelmus** [comment]
I think the reason why altitude is not being read in is that I did not see that field in the file when I wrote the function.  I was looking for a `height` variable and skipped over the `alt` variable.  I'll submit a PR fixing this shortly.

**Comment by kirknorth** [comment]
Okay, just making sure it wasn't an altitude correction fix, calibration issue with original data, or anything of that sort. Thanks @jjhelmus.
