### ISSUE TITLE
add gatefilter to VPT plot

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#633]
Very handy for seeing gatefilter applications. Works for PPI and RHIs.. I may get time to do this by just copying from other.. otherwise this is a placeholder

**Comment by vlouf** [comment]
Hi Scott, 
I was just thinking about that too, also adding gate filter to the add_field method:
radar.add_field('new_field', data_structure, gatefilter=gf)
So that the new field is saved with the gate filter.

**Comment by scollis** [comment]
Thanks to @zssherman this is closed via #645

**Comment by scollis** [comment]
Thanks @zssherman Closing
