### ISSUE TITLE
Moving Example Data to a permanent location

### ISSUE THREAD

**Issue by Rumpkie** [ARM-DOE/pyart#641]
We should move the example data from: https://engineering.arm.gov/~jhelmus/pyart_example_data/
to a permanent location.

**Comment by zssherman** [comment]
@scollis For this, should we have a data folder under examples with all the files? Or maybe a separate data repository. The first option, the files would get downloaded when the pyart repository is cloned, and not sure if that option is desired, seeing as the files are currently separate at the engineering jhelmus link.

**Comment by kmuehlbauer** [comment]
@zssherman A separate repo would indeed be a good solution. Most obvious reason is to not clutter the source code repo with huge data. It works quite well in other packages I maintain. There are different approaches for retrieval though.

**Comment by zssherman** [comment]
@kmuehlbauer Very good point, I like that idea. Yeah a separate repo seems ideal.

**Comment by mgrover1** [comment]
Now that we have this module/in a permanent location, we can close!
