### ISSUE TITLE
/images/no_image.png error when running rebuild_examples.sh

### ISSUE THREAD

**Issue by Rumpkie** [ARM-DOE/pyart#642]
When attempting to rebuild the examples if the user doesn't have the example data in the directory the script errors out with:

`FileNotFoundError: [Errno 2] No such file or directory: 'images/no_image.png'`

The script should either correctly replace the image that wasn't rendered with the no_image.png and let the user know which examples didn't run or error out when it can't find the example file.

**Comment by scollis** [comment]
Thanks @Rumpkie We can start looking into this later this week

**Comment by scollis** [comment]
@zssherman can you investigate please so we can close this issue

**Comment by zssherman** [comment]
Occurs when an example is not created from an error. Closing.
