### ISSUE TITLE
Bug when plotting two or more RadarMapDisplayCartopy.plot_ppi_map axes on same figure

### ISSUE THREAD

**Issue by tjlang** [ARM-DOE/pyart#679]
The following code:
```
dc = pyart.graph.RadarMapDisplay(rad8b)
fig = plt.figure(figsize=(10, 10))
ax1 = fig.add_subplot(211)
dc.plot_ppi_map('reflectivity', ax=ax1, fig=fig, resolution='i')
ax2 = fig.add_subplot(212)
dc.plot_ppi_map('reflectivity', ax=ax2, fig=fig, alpha=0.05, resolution='i')
```
produces the following basemap plot, as expected:
![image](https://user-images.githubusercontent.com/3036387/29587679-4c15a8c2-8754-11e7-9194-6e99c7455373.png)

However, when doing an analogous plot using RadarMapDisplayCartopy:
```
dc = pyart.graph.RadarMapDisplayCartopy(rad8b)
fig = plt.figure(figsize=(10, 10))
ax1 = fig.add_subplot(211)
dc.plot_ppi_map('reflectivity', ax=ax1, fig=fig, resolution='10m')
ax2 = fig.add_subplot(212)
dc.plot_ppi_map('reflectivity', ax=ax2, fig=fig, alpha=0.05, resolution='10m')
```
we get the following plot:
![image](https://user-images.githubusercontent.com/3036387/29587761-81dee89c-8754-11e7-9262-663177305561.png)

What's going on?

**Comment by scollis** [comment]
I think I know.

And it is a bug and a feature. Your axes have no projection so the code 
rejects your axes and puts in its own

https://github.com/ARM-DOE/pyart/blob/master/pyart/graph/radarmapdisplay_cartopy.py#L251

try:

projection = cartopy.crs.LambertConformal(
central_longitude=lon_0,
central_latitude=lat_0)
ax1 = plt.axes(projection=projection)

**Comment by tjlang** [comment]
Thanks! Doing:
```
projection = cartopy.crs.LambertConformal(
    central_longitude=rad8b.longitude['data'][0],
    central_latitude=rad8b.latitude['data'][0])
dc = pyart.graph.RadarMapDisplayCartopy(rad8b)
fig = plt.figure(figsize=(10, 10))
ax1 = fig.add_subplot(211, projection=projection)
dc.plot_ppi_map('reflectivity', ax=ax1, fig=fig, resolution='10m')
ax2 = fig.add_subplot(212, projection=projection)
dc.plot_ppi_map('reflectivity', ax=ax2, fig=fig, alpha=0.05, resolution='10m')
```
produced:
![image](https://user-images.githubusercontent.com/3036387/29618696-9ed56edc-87de-11e7-84c9-1ea53c3d0581.png)

**Comment by amanii84** [comment]
there are no attribute called (pyart.graph.RadarMapDisplayCartopy) only  (pyart.graph.RadarMapDisplaybasemap)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-deee3f0cb72e> in <module>
----> 1 dc = pyart.graph.RadarMapDisplayCartopy(radar)
      2 fig = plt.figure(figsize=(10, 10))
      3 ax1 = fig.add_subplot(211, projection=projection)
      4 dc.plot_ppi_map('reflectivity', ax=ax1, fig=fig, resolution='10m')

AttributeError: module 'pyart.graph' has no attribute 'RadarMapDisplayCartopy'
-----------------------------------------------------------------------------------------------------------
any help please

**Comment by zssherman** [comment]
@amanii84  Module is RadarMapDisplay, the cartopy is no longer in the name as it's the main module radar map backend module.

**Comment by amanii84** [comment]
@zssherman , please can you write it briefly because I do not understand you very well.

**Comment by zssherman** [comment]
@amanii84 
dc = pyart.graph.RadarMapDisplay(radar)

is what it should be

**Comment by amanii84** [comment]
where should I put cartopy to overlap the radar data on the orographic
sorry for this question, I am still a beginner in using radar data

**Comment by zssherman** [comment]
@amanii84 
I would do something similar to this:
https://arm-doe.github.io/pyart/examples/plotting/plot_modify_colorbar.html#sphx-glr-examples-plotting-plot-modify-colorbar-py

And change the projection to the protection you want, and it should work.

**Comment by zssherman** [comment]
The code is very similar, and where the projection is called, just switch out the projection

**Comment by amanii84** [comment]
if you please, I want to make radar data in cartesian coordinates and transform it to NetCDF format.
could you help me?

**Comment by zssherman** [comment]
I would move this to a discussion as this is a separate issue, but follow the example here, for converting to a Cartesian grid:
https://arm-doe.github.io/pyart/examples/mapping/plot_map_one_radar_to_grid.html#sphx-glr-examples-mapping-plot-map-one-radar-to-grid-py

then once you have a grid object do a:
pyart.io.write_grid('file paths, grid)

**Comment by zssherman** [comment]
that will output to a Cartesian netcdf file.

**Comment by amanii84** [comment]
thank you very mush, I will try all these scripts
I appretiate you for all these help.

**Comment by zssherman** [comment]
No problem!

**Comment by amanii84** [comment]
I Try all these scripts and I get the netcdf file but it is not in  Cartesian coordinate the lat , lon dimensions not found , the dimension is X, Y ,Z .
what I shoud do to get the lat, lon dimension.

**Comment by zssherman** [comment]
@amanii84 the gridding functionality is to a Cartesian grid. If you want the lat lon preserved in this file you use:
write_point_lon_lat_alt=True in the grid writing function.

**Comment by amanii84** [comment]
write_point_lon_lat_alt=True
it doesn't working

**Comment by zssherman** [comment]
@amanii84 I would open a discussion here:
https://github.com/ARM-DOE/pyart/discussions
as this is outside the scope of this issue.
And we can discuss more there.
