### ISSUE TITLE
Plot sector from PPI

### ISSUE THREAD

**Issue by nguy** [ARM-DOE/pyart#681]
During the AMS Radar short course, one of the participants asked about the ability to take a PPI scan and plot a sector. This could "_easily_" be done by masking I would think (have to look at the structure a bit), but it could be a nice convenience function to add to the plotting library.

**Comment by nguy** [comment]
Sorry for the delay. 
That's a good idea. One other thought tossing around my head is being able to select a slice of azimuth. If you were to provide a backend to xarray, this would be an easy operation with the `dataframe.sel` method.

**Comment by mgrover1** [comment]
Merged with #670
