### ISSUE TITLE
The circular reference in Radar Class

### ISSUE THREAD

**Issue by hhuangwx** [ARM-DOE/pyart#696]
The LazyLoadDict used in the Radar class causes a circular reference, which will make the memory used by the class never collected by the automatic gc system (known as the memory leakage).  
![image](https://user-images.githubusercontent.com/11309009/34994685-4f062d8e-fb0f-11e7-9669-c8b9ceb48b94.png)

If you are agree with my opinion that the LazyLoadDict should not utilized, I can help to fix the above problem.

**Comment by scollis** [comment]
Thanks @hhuangwx ! @zssherman take a look at this

**Comment by scollis** [comment]
And yes.. a PR would be very welcome..

**Comment by scollis** [comment]
Ha! Your PR found a bigger issue as well thanks to the CI. Numpy's np.fromstring is depricated. 
We need to fix this first. It will not impact CF-Radial.. but it will impact the binary readers.

**Comment by zssherman** [comment]
Closing this for now.
