### ISSUE TITLE
No version of basemap available for python 3.6 in conda

### ISSUE THREAD

**Issue by meteoswiss-mdr** [ARM-DOE/pyart#708]
Hi all,

I think there should be a cautonary note somewhere on that. There is no version of basemap compatible with Python 3.6 in conda:

conda install basemap nose h5py gdal
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - basemap
  - gdal
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

Greetings from Switzerland!

**Comment by scollis** [comment]
Lets look into this. we are managing to test ok in version 3.6 from Conda forge
https://github.com/ARM-DOE/pyart/blob/master/continuous_integration/environment-3.6.yml

gdal has always created issues for me. I wonder if we should deprecate basemap support.. time to sunset Py-ART's usage for sure. I am working on an X-Array bridge for the grid object.. this automagically creates nice cartopy support.

**Comment by kmuehlbauer** [comment]
@meteoswiss-mdr Obviously some of your installed packages doesn't match.
I can create a clean environment with:

`conda create -n basemap basemap gdal h5py numpy`

conda list

```
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.4                      py36_1    conda-forge
basemap                   1.1.0                    py36_3    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
expat                     2.2.5                         0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.4                         0    conda-forge
gdal                      2.2.3                    py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                         1    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5py                      2.7.1                    py36_2    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
icu                       58.2                          0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.3                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libkml                    1.3.0                         6    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.34                        0    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.7                         0    conda-forge
matplotlib                2.1.2                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        7    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openssl                   1.0.2n                        0    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pixman                    0.34.0                        1    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.8                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
setuptools                38.4.0                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
util-linux                2.21                          0  
wheel                     0.30.0                   py36_2    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by karosc** [comment]
I am having a similar issue on windows. I found precompiled versions of basemap [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#basemap), but they are compiled using the most recent numpy 1.14, while pyart is specified to only use 1.12. 

This causes an error when importing pyart, as basemap and pyart use conflicting versions of numpy. Is there any reason not to move up to the most recent numpy version?

**Comment by scollis** [comment]
Sorry to hear @karosc . We will be cutting a new PyART release next week.. hoping this will resolve your issue

**Comment by dopplershift** [comment]
@scollis FYI, conda-forge has stopped pinning particular versions of numpy for the compiled packages; so either a new release or updating the package should allow you to be binary compatible with any of the numpy's.

**Comment by scollis** [comment]
Closing as I assume Py-ART 1.9.0 fixed this... reopen if an issue

**Comment by tjlang** [comment]
Trying to install basemap on a loaner. Brought in Py-ART 1.9.1 via conda, but then:

loaner @ Radar$conda install basemap
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - arm_pyart
  - basemap
  - shapely
Use "conda info <package>" to see the dependencies for each package.

**Comment by zssherman** [comment]
@tjlang Can you try conda install -c conda-forge basemap ? I tried to install basemap using the anaconda cloud with conda install basemap and it defaulted pyart to 1.9.0, which I think is hinting at a possible issue. But when I tried to download basemap using conda-forge I was able to download pyart 1.9.1 and basemap. The basemap in the anaconda cloud is outdated compared to conda-forge, so I'm curious if this is maybe causing the conflict. I'll continue looking more into it.

**Comment by tjlang** [comment]
@zssherman That worked! I also had to do this separately to get the hi-res data:
`conda install -c conda-forge basemap-data-hires`

But we are in business. Thanks for the timely response.

I do agree that `Basemap` likely will need to be retired from `pyart`, likely sooner rather than later.

**Comment by zssherman** [comment]
@tjlang No problem! And I completely forgot about basemap-data-hires, and I agree. I'll talk with @scollis and get an idea of when Py-ART will retire basemap. I believe basemap is no longer being supported in 2020, but Py-ART will probably retire it before then.

**Comment by scollis** [comment]
Gotta deal with retiring python 2.7 first ;)

-sent from a mobile device-

**Comment by jamessong** [comment]
it doesn't work with 3.7!!

**Comment by scollis** [comment]
Well aware @jamessong We will be extracting basemap soon
@zssherman is compiling a to-do list and we will be sprinting this shortly

**Comment by jamessong** [comment]
Can anyone provide a workable solution? Do I need to downgrade to python 2.7 again?

**Comment by scollis** [comment]
Use 3.6

-sent from a mobile device-

**Comment by scollis** [comment]
Take a look here.. https://github.com/openradar/aus-open-radar-science-school/blob/master/install.rst
uses this YML:
https://github.com/openradar/aus-open-radar-science-school/blob/master/pyart-2018.yml

That will get you up with no worries.

**Comment by scollis** [comment]
Otherwise if you want latest use this:
https://github.com/EVS-ATMOS/phase-testbed/blob/master/pyart_full.yml

This will attempt to compile Py-ART from source

**Comment by jamessong** [comment]
right now I am getting KeyError: 'PROJ_LIB'   -  this is wasting our time and I have found multiple places people complaining about this for years ... can this be fixed forever?

**Comment by scollis** [comment]
Fell free to fix it in basemap. This is not a pyart issue. It’s a conda-forge issue 

 Im so sorry our free and open software is wasting your time 

-sent from a mobile device-

**Comment by jamessong** [comment]
... # Draw barbs
... m.barbs(x,y,u,v, length=7, color='red')
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 576, in with_transform
    return plotfunc(self,x,y,u,v,*args,**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 3786, in barbs
    self._restore_hold(ax)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 3229, in _restore_hold
    ax._hold = self._tmp_hold
AttributeError: can't set attribute

**Comment by jamessong** [comment]
> Fell free to fix it in basemap. This is not a pyart issue. It’s a conda-forge issue Im so sorry our free and open software is wasting your time
> […](#)
> -sent from a mobile device-
> On Nov 25, 2018, at 6:06 PM, jamessong ***@***.***> wrote: right now I am getting KeyError: 'PROJ_LIB' - this is wasting our time and I have found multiple places people complaining about this for years ... can this be fixed forever? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

I am new to the installation of basemap, can anyone point me to the right way of using either basemap or pyart?  Is pyart going to replace or already replacing basemap?

**Comment by scollis** [comment]
James please use the email list pyart-users@googlegroups.com 

-sent from a mobile device-
