### ISSUE TITLE
Create "Cheat Sheet" hand out

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#712]
We need a hand out sheet like this:
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

I recall seeing a template for this.. We need to track this down as it will be a very handy hand out. Pun intended

**Comment by kmuehlbauer** [comment]
@scollis See here: https://gitter.im/openradar/Lobby I sent you our template last year.

**Comment by scollis** [comment]
Yay! I knew you did I was just too disorganized to remember where.. Much appreciated @kmuehlbauer !

**Comment by kmuehlbauer** [comment]
:+1: Let me know, if you buried it too deep.

**Comment by zssherman** [comment]
Cheatsheet is done and can be found here:
https://github.com/ARM-DOE/pyart/blob/master/guides/pyart_cheatsheet.pdf
Closing
