### ISSUE TITLE
python 3.6 read_nexrad_archive

### ISSUE THREAD

**Issue by swnesbitt** [ARM-DOE/pyart#714]
Getting a bazillion depreciation warnings when trying to read a nexrad level2 file using `pyart.io.read_nexrad_archive(filename)` in python 3.6

```
/Users/snesbitt/anaconda/lib/python3.6/site-packages/pyart/io/nexrad_level2.py:619: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(buf[ptr2: ptr2 + ngates], '>u1')
```

**Comment by swnesbitt** [comment]
obvs can do this to hide 😄 
```
import warnings
warnings.filterwarnings('ignore')
```

**Comment by scollis** [comment]
Update time for you. We fixed this in #700 
Py-ART 1.9.0 on conda-forge has this fixed.

**Comment by scollis** [comment]
print(pyart.__version__)

**Comment by zssherman** [comment]
@scollis beat me to it.

**Comment by scollis** [comment]
I love answering the easy ones.

**Comment by scollis** [comment]
@swnesbitt Let me know if this works so I can close the issue.

**Comment by swnesbitt** [comment]
```
print(pyart.version)
<module 'pyart.version' from '/Users/snesbitt/anaconda/lib/python3.6/site-packages/pyart/version.py'>
```

**Comment by scollis** [comment]
Yeah.. sorry 
`pyart.__version__`

**Comment by swnesbitt** [comment]
'1.9.0.dev+35d6f51'

**Comment by scollis** [comment]
Hmm ok .. That is odd then.. did you install from source or conda-forge?

**Comment by swnesbitt** [comment]
source

**Comment by swnesbitt** [comment]
trying conda-forge

**Comment by swnesbitt** [comment]
that fixed it 👍
