### ISSUE TITLE
wradlib release 1.0.0

### ISSUE THREAD

**Issue by kmuehlbauer** [ARM-DOE/pyart#722]
wradlib release 1.0.0 is on it's way. There are breaking changes in this version which also effect pyart rainbow reader. The changes were due to PEP8 conformity, so everything will work after introducing these changes.

I will introduce the necessary changes next week via PR. Sorry for any inconvenience.

**Comment by kmuehlbauer** [comment]
@scollis You might assign me to this.

**Comment by kmuehlbauer** [comment]
@scollis How should I implement this? A version check would be best. So things won't break environments with old wradlib.

**Comment by scollis** [comment]
Hi folks. On vacation will get to this next week

-sent from a mobile device-
