### ISSUE TITLE
How to speed up gates_to_grid?

### ISSUE THREAD

**Issue by lovechang1986** [ARM-DOE/pyart#741]

**Comment by zssherman** [comment]
@lovechang1986 If your using nearest neighbor as the weighting function, currently it has not been optimized in the c code. Besides that, gates_to_grid/map_gates_to_grid was optimized in the past using cython and c I believe. Speeding them up, I'm not sure, I would have to take a look.

**Comment by scollis** [comment]
Hey @lovechang1986 This is not the right place for asking these questions. Please use the email list for questions like this.
