### ISSUE TITLE
written error

### ISSUE THREAD

**Issue by zxdawn** [ARM-DOE/pyart#742]
https://github.com/ARM-DOE/pyart/blob/dbe4d70eccc1b88260d44720cf133694d127df0a/pyart/graph/radarmapdisplay.py#L264

width = (x.max() - x.min()) * 1000.

**Comment by scollis** [comment]
Nice catch! 
I am going to make this a "Great First Pull Request" as this is something a beginner could fix. We will leave this open a week then @zssherman will fix it if no one volunteers
