### ISSUE TITLE
Rely on .pyx file and dynamically create .c files using cython

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#759]
see #758 for what lead to this.. I am very interested in @jjhelmus's views on this. 

pro: 
* Folks can just edit pyx files and only commit those. 
* we get the latest bells and whistles from new cython versions
* Lighter weight and true line counts

Cons: 
* cython becomes a dependancy
* More work: Need to update release and testing to generate .c files on the fly

**Comment by dopplershift** [comment]
Pro: Git history not bloated by changes to generated code

**Comment by ngoldbaum** [comment]
For the last con point, here’s the bit in yt’s setup.py file that handles compiling the cython code for the sdist: https://github.com/yt-project/yt/blob/master/setup.py#L337

**Comment by scollis** [comment]
Of course! I would expect that Jonathan :-)

-sent from a mobile device-

**Comment by scollis** [comment]
@zssherman can we close?

**Comment by zssherman** [comment]
This wasn't done, but still would be a good idea to do, so I would leave it open.

**Comment by scollis** [comment]
It's yours now! I will write this into our new ARM ENG

**Comment by scollis** [comment]
but don't let that stop you from doing it if you get keen in the meanwhile

**Comment by zssherman** [comment]
closing in favor of #823
