### ISSUE TITLE
Mdv read problem use pyart.io.mdv_common.MdvFile()

### ISSUE THREAD

**Issue by Athenaplot** [ARM-DOE/pyart#760]
when I run the function 
`a=pyart.io.common_mdv.MdvField('xxx.mdv',read_fields=True)`
I got the error below:
![2018-08-10 15-34-09](https://user-images.githubusercontent.com/31769682/43951975-23702e9a-9cc7-11e8-89ce-b95c9de4554e.png)

then i rewrite the some code in common_mdv.py which aims to print the variable `compr_info` as below:
![2018-08-10 18-06-11](https://user-images.githubusercontent.com/31769682/43952338-3fb0ba92-9cc8-11e8-831a-2ff01ab414eb.png)

then ,i got the information about `compr_info` ,and find out why i got error :+1: `NotImplementedError:unknown compression mode` 
![2018-08-10 18-11-31](https://user-images.githubusercontent.com/31769682/43952563-e2bf5afe-9cc8-11e8-81b2-1e19b5e4da6b.png)
it seems that while reading the third vlevel data, `compr_info` has the key 'magic_cookie' with value of 254,which is not the compression forms defined in the codes. 
I don't kown how to solve the problem,or what kind of compression `254` means. how to decompressed this kind compression data.    begging for solution!!!!  a little hurry

**Comment by scollis** [comment]
No idea. Have you tried using RadX? What generated this file?

**Comment by Athenaplot** [comment]
i haven't use the RadX. this file is generated by c++ , the version is about 2010. I checked someother Mdv file , when reading the thirth level data, the `magci_cookie` is not standard, and the values changes each time. the first two level's `magic_cookie`  are same.   anyway ,i will try my best to decompress these unkown `magic_cookie`, but , when i use c++ to read the file, i create a DsMdvx class, and set the compressiontype by the code `mdvxRadar.setReadCompressionType(Mdvx::COMPRESSION_NONE)`, it can work well. i can't figure out the difference between `magic_cookie in python `  and `setReadCompression in C++ `. Dose that mean i can read the Mdvfile  straightly no matter what kind compressiontype is.? 

My English is not good,i don't know i make it clear. anyway, I appreciate your response, and when i  discovered the pyart three months ago ,it striked me. thanks your job,it's so big big good job. @scollis

**Comment by liliaow567** [comment]
Hello, dude，has the problem been solved? I have the same problem with yours.

**Comment by Athenaplot** [comment]
Sorry ,budy,i'm trying ,if i solve the problem,i will share it with you as soon as possible. so do you? ,right?

**Comment by liliaow567** [comment]
I think im too busy to take it, so sorry @Athenaplot
