### ISSUE TITLE
Issue with file handing rainbow files using wradlib

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#762]
https://github.com/ARM-DOE/pyart/blob/master/pyart/aux_io/rainbow_wrl.py#L153

proposed by our friends at MeteoSwiss
```
I propose to solve the issue by passing the file handle, not the file name to wradlib, i.e.:
with open(filename, 'rb') as fid:
rbf = read_rainbow(fid, loaddata=True)
Greetings from Switzerland!
```

**Comment by scollis** [comment]
I'll hack this later this week unless anyone wants to do it

**Comment by kmuehlbauer** [comment]
JFTR: @scollis wradlib release 1.1.0 is out and fixes the underlying problem.

**Comment by scollis** [comment]
Awesome . We will do some testing next week 

-sent from a mobile device-

**Comment by zssherman** [comment]
The wradlib update fixed this. Closing
