### ISSUE TITLE
Make basemap an optional dependancy

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#766]
Basemap is having more issues which is expected as we head to end of life. It need to be made optional, the same as Cartopy

**Comment by scollis** [comment]
Key requirement from our FNMOC stakeholders:
Side by side examples of plotting using Basemap and Cartopy to ease the transition

**Comment by scollis** [comment]
@zssherman can we close this via #786 ?

**Comment by zssherman** [comment]
@scollis Not yet. @jhemedin can you do a pull request to put the plot_ppi_cartopy_with_rings.py example you created into the examples folder under plotting. And for the top add:
# Author <your name>
# License: BSD 3 clause

**Comment by zssherman** [comment]
@scollis And the graph pull request needs to be accepted before his code would work.

**Comment by zssherman** [comment]
Basemap is now optional with cartopy being favored. Closing.
