### ISSUE TITLE
NEXRAD_DICTIONARY dictionary unit in altitude.

### ISSUE THREAD

**Issue by miaoneng** [ARM-DOE/pyart#830]
It is a really old topic but I recently noticed this issue when doing turburlance computation. The altitude field provided in NEXRAD_LOCATION is in feet, not in meters, but looks like being assumed as meters. 
I need double-check in raw msg31 when altitude is encoded, it is in feet or in meters, but I am betting it is in feet because RPG uses feet as its standard unit. But at least for this issue, it is a trivial fix.

**Comment by zssherman** [comment]
Fixed in #924 closing.
