### ISSUE TITLE
Writing specific fields

### ISSUE THREAD

**Issue by bdolan44** [ARM-DOE/pyart#850]
I think it would be very useful to be able to specify the fields to write out. Something along the lines of 

pyart.io.write(radar,fields = ['reflectivity','differential_reflectivity','velocity']")

**Comment by scollis** [comment]
Great idea! Assigning @zssherman

**Comment by zssherman** [comment]
Sounds good to me, I don't think it will be difficult to implement at all. I will take a look.

**Comment by swnesbitt** [comment]
Chiming in here – would it be more useful to write a function that selected fields from a radar object.  This could make it easier to also do memory management, etc.

This could follow the xarray syntax, for example

radar1.sel(field=[‘reflectivity’,’velocity’])
and maybe in the future
radar1.sel(azimuth=slice([90,150]))
radar1.sel(sweep=slice(1,3))

This could easily be put into a one-liner
pyart.io.write(radar1.sel(fields = ['reflectivity','differential_reflectivity','velocity']))
or eventually (to follow pandas/xarray syntax)
radar1.sel(field=[‘reflectivity’,‘velocity’]).to_cfradial(‘file.nc’)

Just my two pennies,
-Steve

**Comment by zssherman** [comment]
@swnesbitt I do like that idea, and now with xarray being used for the grids, its already a dependency. I'll see what I can code up.

**Comment by bdolan44** [comment]
Yes, 1-up on @swnesbitt's comment. That would be fantastic.

**Comment by zssherman** [comment]
Completed in #1319 , closing.

**Comment by mgrover1** [comment]
@bdolan44 this is now available in the latest release of Py-ART

**Comment by bdolan44** [comment]
Fantastic! I was just thinking about this functionality again recently. Thanks!
