### ISSUE TITLE
about velocity dealiasing

### ISSUE THREAD

**Issue by huihuojia** [ARM-DOE/pyart#854]
When I use "pyart.correct.dealias_region_based" to do the velocity dealiasing of NEXRAD data, I got this warning message, what does it mean?

/Applications/anaconda3/lib/python3.7/site-packages/pyart/correct/region_dealias.py:302: UserWarning: Velocities outside of the Nyquist interval found in sweep 7.

I thought there're always velocities beyond the Nyquist velocity after unfolding.

Jia

**Comment by scollis** [comment]
No there are not.. if the file is no dealiased and if the nyquist is correct in the metadata there should be no values outside (except _FillValue)... If nyquist is incorrect in the file it can be overridden with nyquist_vel 
http://arm-doe.github.io/pyart-docs-travis/dev_reference/generated/pyart.correct.region_dealias.dealias_region_based.html
