### ISSUE TITLE
strange behaviour of grid_from_radars

### ISSUE THREAD

**Issue by meteoDaniel** [ARM-DOE/pyart#857]
I want to create a composite of different radar's from germany. 
[test_data_odim_h5.zip](https://github.com/ARM-DOE/pyart/files/3439100/test_data_odim_h5.zip)

```
from matplotlib import pyplot as plt
from pyart.aux_io import odim_h5
from pyart.map import grid_from_radars

file_essen = 'ras07-vol5minng01_sweeph5onem_dbzh_00-2019072809255700-ess-10410-hd5'
file_neu = 'ras07-vol5minng01_sweeph5onem_dbzh_00-2019072809255700-neu-10557-hd5'
file_flb = 'ras07-vol5minng01_sweeph5onem_dbzh_00-2019072809205700-fld-10440-hd5'

data_ess = odim_h5.read_odim_h5(file_essen)
data_neu = odim_h5.read_odim_h5(file_neu)
data_flb = odim_h5.read_odim_h5(file_flb)



data_grid = grid_from_radars((data_ess, data_neu, data_flb),
                             grid_shape=(1, 800, 800),
                             grid_limits=(
                             (0, 15000), (-100000, 100000), (-100000, 100000)),
                             grid_origin=(50.939514, 7.339244),
                             gridding_algo='map_gates_to_grid')

fig = plt.figure()
ax = fig.add_subplot(111)
ax.imshow(data_grid.fields['reflectivity']['data'][0],
          origin='lower', vmin=0, vmax=48)
```
My expectation was to get gridded data of all heights by using (0, 15000) as z limit. But the gridded data is near to zero. If i change zlim to ``(3000, 3000)``` a slice around the radar is on the map.
![Figure_1-9](https://user-images.githubusercontent.com/27021858/62005988-0cf3c580-b13b-11e9-98ed-0a9ea1de8866.png)

**Comment by swnesbitt** [comment]
Hi meteoDaniel,

The tuple given to the keyword argument grid_shape

grid_shape=(1, 800, 800),

Controls the number of points in the z, x, and y directions,. respectively. If you increase 1 to n, you will get n levels equally spaced between the first tuple given in the keyword argument grid_limits (1, 150000). A spacing of 1 km would mean 16 levels.

Cheers,
-Steve

Get Outlook for Android<https://aka.ms/ghei36>

STEVE NESBITT
Professor

Department of Atmospheric Sciences
University of Illinois at Urbana-Champaign

3060 Natural History Building | M/C 104
1301 W Green St
Urbana, IL 61801

217.244.3740 | fax: 217.244.1752 | snesbitt@illinois.edu
www.atmos.illinois.edu<http://www.atmos.illinois.edu> | snesbitt.web.illinois.edu

Under the Illinois Freedom of Information Act any written communication to or from university employees regarding university business is a public record and may be subject to public disclosure.


________________________________
