### ISSUE TITLE
'constant_roi' argument should override 'roi_func' in gates_to_grid.py

### ISSUE THREAD

**Issue by vlouf** [ARM-DOE/pyart#863]
In gates_to_grid.py there are 2 arguments:
`roi_func='dist_beam', constant_roi=500.,`

Right now, if you define a constant_roi, the default `roi_func` is still 'dist_beam' and so the constant_roi that is defined is useless. Defining a constant_roi should switch automatically the roi_func to 'constant'.

cc. @robwarrenwx 

I propose to change the default of constant_roi to None: `constant_roi=None` and then in the function `map_gates_to_grid` to have something like that:
```python
if constant_roi is not None:
    roi_func = 'constant'
else:
    constant_roi = 500
```

**Comment by scollis** [comment]
Closed by #864
