### ISSUE TITLE
Speed up of "estimate_noise_hs74"

### ISSUE THREAD

**Issue by meteoswiss-mdr** [ARM-DOE/pyart#872]
Hi all,

In my own version of Py-ART I have modified the code of pyart/util/hildebrand_sekhon.py in order to speed it up. Check out:

https://github.com/meteoswiss-mdr/pyart/blob/master/pyart/util/hildebrand_sekhon.py

The resultant code is significantly faster. You may want to add it up in Py-ART.

Greetings from Switzerland!

**Comment by scollis** [comment]
Thanks Jordi! 

-sent from a mobile device-

**Comment by zssherman** [comment]
Thanks Jordi! I just got to figure out how to commit your changes while maintaining the commit log, but without pulling the html and spectra changes.

**Comment by zssherman** [comment]
Was merged in #877 closing.
