### ISSUE TITLE
About field of“temperature” in attenuation module

### ISSUE THREAD

**Issue by sysumeteo** [ARM-DOE/pyart#881]
It seems like there is a tiny bug in the  "pyart.correct.calculate_attenuation" ,which the function "calculate_attenuation_zphi" get field name for "temperature". Hower there is no filed name of "temperature" in the dict DEFAULT_FIELD_NAMES of "default_config.py".
Additionally, i think it would be an usefully work to design a method to ingest sounding data for the "temperature" field  since most of radar data do not contain it intrinsically

**Comment by meteoswiss-mdr** [comment]
Hi @sysumeteo,

Probably it is time to add officially the temperature field in default_config.py. 

As for the temperature field, is a bit up to you what you want to use. I use temperature from NWP models interpolated into the radar grid. I think out there there is software to create a gridded field out of sounding data.

**Comment by sysumeteo** [comment]
Got it, mapping sounding data to radar coordinate is not a difficult task and i can also asign a edited config file for attenuation.py manually.
