### ISSUE TITLE
Speed up ‘Nearest’ method for mapping and add it into ‘map_gates_to_grid’？

### ISSUE THREAD

**Issue by sysumeteo** [ARM-DOE/pyart#888]
‘Nearest’ method is quite useful for mapping FHC data, but unfortunately  was supported only by   algorithm 'map_to_grid ' which is several times slower than 'map_gates_to_grid'. Is there any plan to speed up 'Nearest' method and add it into ‘map_gates_to_grid’?
BTW:  Function 'grid_from_radars' use algorithm 'map_gates_to_grid'  by default, but with no suggestion about its incompatible with 'Nearest' method in the LATEST DOC. That  keeps confusing me until i found annotation in the code. I think adding some suggestion in the doc would be better.

**Comment by zssherman** [comment]
Hi @sysumeteo Nearest should be in map_gates_to_grid, https://github.com/ARM-DOE/pyart/blob/master/pyart/map/gates_to_grid.py#L170 if its not working for some reason, then there possibly is a bug then. I will take a look at the docs too.

**Comment by sysumeteo** [comment]
@zssherman  My inattention for the function ! Actually map_gates_to_grid support  'Nearest' method, and run as fast as map_gate_to_grid should be.But another problem is that ,'Nearest' method perform quite different between 'map_gate_to_grid' and 'map_to_grid'. 
My code and plots are showed below:
 The first FH plot is  corresponding to 'Nearest' method of 'map_to_grid',while the second one is corresponding to 'Nearest' method of 'map_gate_to grid' and the third plot is for 'Barnes2' of 'map_gate_to grid' .

        grid=pyart.map.grid_from_radars((radar1,),grid_shape=(nz,nx,ny),grid_limits=((min_z,max_z),(min_x,max_x),(min_y,max_y)),weighting_function='Barnes2')       
        #grid_FH=pyart.map.grid_from_radars((radar1,),grid_shape=(nz,nx,ny),grid_limits=((min_z,max_z),(min_x,max_x),(min_y,max_y)),
        #       fields=['FH'],gridding_algo='map_to_grid',weighting_function='Nearest')        
        grid_FH=pyart.map.grid_from_radars((radar1,),grid_shape=(nz,nx,ny),grid_limits=((min_z,max_z),(min_x,max_x),(min_y,max_y)),
               fields=['FH'],weighting_function='Nearest')

![grid_plot_FH20150516074750 (2)](https://user-images.githubusercontent.com/14120258/71565309-62684000-2ae8-11ea-9220-3d7fb380e212.jpg)
![grid_plot_FH20150516074750](https://user-images.githubusercontent.com/14120258/71565311-68f6b780-2ae8-11ea-9e34-ed0b5dee0e75.jpg)
![grid_plot_Zh20150516074750](https://user-images.githubusercontent.com/14120258/71565314-74e27980-2ae8-11ea-8b22-118b3c1dc38c.jpg)

**Comment by zssherman** [comment]
Hmm, I'll have to look into that. I'm not sure why the two plots are giving different results for Nearest.

**Comment by zssherman** [comment]
Fixed in #934 closing.
