### ISSUE TITLE
ODIM h5 range and azimuth sampling

### ISSUE THREAD

**Issue by vlouf** [ARM-DOE/pyart#897]
(cc. @marack)

In the ODIM specification, rstart is "The range (km) of the start of the first range bin", which means that this is the 'front' edge of the sample, not the centre of the bin  (p. 12 of the ODIM specification format v23). 

The way `pyart.aux_io.read_odim_h5` works right now is by considering the range and azimuth sampling from the front edge of the bin. Just to be sure: we have to consider that the range and azimuth from the Radar object is pointing to the center of a bin, not one of the edges? Because if the value of `radar.range['data'][0]` is 0 (which is what we have today), that's going to lead to troubles.

'astart' is conceived the same way for the azimuth. However, astart is an optional argument found in the 'how' group and not the 'where' group like the others... If 'astart' is not provided you can assume that the front edge of the first ray is 0.

I've worked on modifications for the code, I'll send a PR.

**Comment by scollis** [comment]
Closed via #898 Thanks again @vlouf
