### ISSUE TITLE
Link to MPL in setup.py

### ISSUE THREAD

**Issue by scollis** [ARM-DOE/pyart#910]
See this tweet:
https://twitter.com/story645/status/1234869245449818112
Hey folks who maintain libraries built on top of 
@matplotlib
 that are packaged on 
@pypi
, I need a huge to me favor. 
If you'd include a 'Framework::Matplotlib' classifier in your

 http://setup.py if it exists, please comment at

**Comment by scollis** [comment]
@zssherman can you look after this

**Comment by zssherman** [comment]
Yep, I'll do the changes.

**Comment by zssherman** [comment]
This was done in #912 closing.
