### ISSUE TITLE
Error in basic ingest example

### ISSUE THREAD

**Issue by louiswicker** [ARM-DOE/pyart#916]
I am trying to write a ingest for MRMS radial velocity, and I was using the example in

http://arm-doe.github.io/pyart-docs-travis/notebooks/basic_ingest_using_test_radar_object.html

The n_azim and n_gates arguments to pyart.testing.make_empty_ppi_radar are reversed.

**Comment by scollis** [comment]
Thanks @louiswicker !
@rcjackson can you take a look at this.. @IreneCrisologo can you help as this will be very useful for us.

**Comment by zssherman** [comment]
Ah yep, I see that, my bad, I will do a pull request with the fix

**Comment by zssherman** [comment]
Fixed and new notebooks are on the site now, closing.
