### ISSUE TITLE
Example Link Broken

### ISSUE THREAD

**Issue by julienchastang** [ARM-DOE/pyart#918]
In the readme

Examples: http://arm-doe.github.io/pyart/dev/auto_examples/index.html

yields a `404` Page not found error.

**Comment by zssherman** [comment]
Hi @julienchastang , thanks for catching this! I pushed a commit and this should be fixed now.

**Comment by julienchastang** [comment]
Thanks @zssherman. While I have your attention, where are the data referenced in the example code (e.g., `sgpcsaprsurcmacI7.c0.20110520.095101.nc`). It may be obvious, but I don't see it.

**Comment by zssherman** [comment]
@julienchastang Not a problem, and the data used in the examples can be found here:
https://engineering.arm.gov/~jhelmus/pyart_example_data/
