### ISSUE TITLE
Radar Elevation Misread for some Nexrad Level 3 Files

### ISSUE THREAD

**Issue by dcedgren** [ARM-DOE/pyart#923]
Currently nexrad_level3.py assumes Halfword 30 of the Product Description block corresponds to the sweep elevation angle. In fact, it is a product-dependent parameter and this is only the case for some files. For some Nexrad Level 3 files there is not really a defined elevation. Product #176 (DPR), for example, and others.

There's a whole long list of product-dependent parameters in the ICD (Table V, which goes on for over 20 pages) and how to decode them from which halfwords. Some of these parameters are just file metadata, like compression information, but a lot of them are meteorological metadata, like start and end of precipitation or mean field bias or max velocity. It would be interesting to incorporate all these into Pyart, but it would be a fair bit of work. (Probably not hard, just a lot of putting the table into code.)

Unless someone is enthusiastic about this I recommend instead for the time being inserting logic that unless this file is one of the products for which halfword 30 corresponds to sweep elevation angle to set the radar object's elevation equal to zero or none.

**Comment by zssherman** [comment]
Pull request has been merged, can reopen if needed. Closing for now.
