### ISSUE TITLE
Weighting Function discrepancy between map_gates_to_grid and map_to_grid

### ISSUE THREAD

**Issue by cptmedic** [ARM-DOE/pyart#930]
Greetings,

There appears to be a slight discrepancy in map_gates_to_grid when using nearest as the weighting function when compared to map_to_grid at the same grid_limits. 

map_gates_to_grid with nearest weighting (producing weird rays):
![map_gates_to_grid with nearest weighting](https://09913886399444730182.googlegroups.com/attach/6820a437a1a35/out3_gates.png?part=0.1&view=1&vt=ANaJVrGg-XjDTKK4_x9Y-C825uFZSuMFp3ouGRMTgukf_6kHgLwrG4aa3sGH2OxpOT42RRdYM89b_ouNwMx59_cuwfFQ9ocju4hnux9VX1JUhcQkVlR5C1U)

map_to_grid with nearest weighting (data is seamless):
![map_to_grid with nearest weighting](https://09913886399444730182.googlegroups.com/attach/6820a437a1a35/out3_reg.png?part=0.2&view=1&vt=ANaJVrHbHGLYGpI0NMJOQYOuhvSSbaj7jPfDC_4TvYctl9GLWQad6ggfoTohrnWscTaRLyF3KxMbEolKFW-VFelsA2KGyr6KCI7T9GlLcexVEhWR1FdW5vs)

These are two examples with the same grid_limit the only difference is the function used.

Also discussed at https://groups.google.com/forum/#!topic/pyart-users/bQJ_1JuAYAg

**Comment by zssherman** [comment]
@cptmedic Thanks again for submitting this! We will take a look at the code and see what could be causing this.

**Comment by zssherman** [comment]
Hi @cptmedic, this should now be fixed in #934
