### ISSUE TITLE
map_gates_to_grid creates blobish edges when weight function set to nearest

### ISSUE THREAD

**Issue by cptmedic** [ARM-DOE/pyart#942]
Good evening,

Zach asked that I create a Github Issue for the following issue. 

Previously when generating a geotiff, map_gates_to_grid would generate a radar file with blue aliasing throughout (pictured below):
![image](https://user-images.githubusercontent.com/27046411/86694470-41216880-bfd1-11ea-8f20-8ed4a4c9c7a9.png)

Merge Request #934 fixed the blue aliasing, but seemed to introduce a new issue where edges of storms would be blobish, and filtering did not remove it.
![image](https://user-images.githubusercontent.com/27046411/86694773-8ba2e500-bfd1-11ea-87ab-a837cf769d81.png)

Changing the algorithm to map_to_grid produces an accurate reflection of the storm, but takes a significantly longer time to generate:
![image](https://user-images.githubusercontent.com/27046411/86695016-c73daf00-bfd1-11ea-9fd4-d1997fd2922b.png)

It appears that there is an issue somewhere with the map_gates_to_grid cython code that is causing the distortion at the boundaries to radar returns.

**Comment by zssherman** [comment]
Thanks @cptmedic! @rcjackson this is in the nearest neighbor cython code whether you get a chance probably after the conference this week if we can work together and sprint to fix this?

**Comment by zssherman** [comment]
@cptmedic This issue might have been found, can you share this file or how are you obtaining the file in the top two images?

**Comment by zssherman** [comment]
To test it out

**Comment by cptmedic** [comment]
@zssherman I have emailed you the python script in it's entirety

**Comment by zssherman** [comment]
@cptmedic In #947 this should now be fix! I have to push out a release still, but in the mean time you can get the fix by git cloning and installing the pyart repo itself.

**Comment by cptmedic** [comment]
Installed from repo source and can confirm it works great! Thanks guys!
