### ISSUE TITLE
cannot install pyart as part of requirements.txt because of missing numpy

### ISSUE THREAD

**Issue by kracwarlock** [ARM-DOE/pyart#951]
https://github.com/ARM-DOE/pyart/blob/3bbab4a012349559874e0923b5a5c4f1962d6540/setup.py#L165
`pyart` imports `numpy` in `setup.py` so if you are setting up `arm_pyart` within a `requirements.txt` file it will fail since `numpy` is not pre-installed. it would be better if numpy could be listed as a dependency instead and python's distutils used to setup the package.

**Comment by zssherman** [comment]
@kracwarlock Yeah, I agree, we do plan on moving the setup.py to setuptools in the future. Just sadly haven't gotten to it yet.

**Comment by Vforcell** [comment]
@kracwarlock @zssherman The same problem is persisting for me. Do you have any update on that issue ?

**Comment by zssherman** [comment]
Closing in favor of #823
