### ISSUE TITLE
Error reading NOAA P3 tail doppler radar data

### ISSUE THREAD

**Issue by mwilson14** [ARM-DOE/pyart#962]
Hi everyone,

I've been working with some of the P3 radar data from TORUS using PyART, and when I first tried reading in one of the files I got this error:

![image](https://user-images.githubusercontent.com/25419751/94454117-17fb1900-0177-11eb-9ef4-2721de82a021.png)

I was able to fix it by changing the call to "np.rec.frombuffer" in line 47 of _sigmet_noaa_hh.py to "np.frombuffer", so I thought I'd put that here in case anyone else ran into the same issue.

**Comment by zssherman** [comment]
Hi @mwilson14 yeah that looks like the submodule was changed so, I think your fix will work. I'll do a PR and author it as you so you get PR credit.

**Comment by mwilson14** [comment]
Thanks! I'm just really glad that the fix turned out to be as small of a change as it was.

**Comment by zssherman** [comment]
Was fixed in #963 closing.
