### ISSUE TITLE
Comparation list and None in cfradial.py

### ISSUE THREAD

**Issue by rafatoshio** [ARM-DOE/pyart#986]
Hi,

using pyart.io.auto_read.read with "exclude_fields" argument it raises TypeError.

Looking further it seems that cfradial.py at line 275 has a comparation with potential NoneType

`if key not in include_fields`

I suggest change it to:

`if include_fields is None or key not in include_fields`

**Comment by zssherman** [comment]
@rafatoshio Thanks, I'll take a look, it might have been a bug in the original code.

**Comment by zssherman** [comment]
Has been fixed, closing.
